### ISSUE TITLE
Unable to launch HDOS or RuneLite from Jages launcher

### ISSUE THREAD

**Issue by RonnieLima** [TormStorm/jagex-launcher-linux#103]
**Describe the bug**
When launching Runelite or HDOS from the Jagex Launcher I receive a Java error

**To Reproduce**
1. Go to Jagex Launcher
2. Launch either HDOS or Runelite
3. 
4. ERROR:
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-21-openjdk/lib/libnio.so: /usr/lib/jvm/java-21-openjdk/lib/libnio.so: undefined symbol: reuseport_available

**Expected behavior**
Runelite or HDOS launches

**Screenshots**
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/20389879/7f7bde0e-6731-4a6f-a948-2a25ca268aa1)

**Hardware information**
[System]
OS:              EndeavourOS rolling rolling
Arch:            x86_64
Kernel:          6.5.7-arch1-1
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             15.5 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.113.01
OpenGL Core:     4.6.0 NVIDIA 535.113.01
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.113.01
Vulkan Version:  1.3.264
Vulkan Drivers:  NVIDIA GeForce RTX 3060 Ti (1.3.242)

**Additional context**

**Comment by nmlynch94** [comment]
Try disabling “prefer system libraries”. There is a version of Java 11 included in the Lutris runtime, but it looks like your system is has Java 21 which I don’t think HDOS is compatible.

**Comment by Kalln** [comment]
> Try disabling “prefer system libraries”. There is a version of Java 11 included in the Lutris runtime, but it looks like your system is has Java 21 which I don’t think HDOS is compatible with.

This solved it for me.  Couldn't launch either HDOS or RL. But disabling "prefer system libraries" solved it. Thanks for your help.

**Comment by nmlynch94** [comment]
No problem! @TormStorm it may be worth adding a note about this on the README for people who aren't using flatpak Lutris.

**Comment by RonnieLima** [comment]
> Try disabling “prefer system libraries”. There is a version of Java 11 included in the Lutris runtime, but it looks like your system is has Java 21 which I don’t think HDOS is compatible with.

This fixed it!  Thank you so much!
