### ISSUE TITLE
Command exited with code 1024 when installing Jagex launcher

### ISSUE THREAD

**Issue by Gubb262** [TormStorm/jagex-launcher-linux#111]
**Describe the bug**
When installing Jagex Launcher using the jagex-lancher.yml file I receive "Command exited with code 1024"

**To Reproduce**
1. Go to "+" in the top left
2. Click on 'Install from script'
3. Select jagex-launcher.yml

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/133971281/2fa42685-4451-4083-8ed2-c9c0e5102c70)

**Expected behavior**
Jagex Launcher installs and is functioning

**Screenshots**

**Hardware information**
[System]
OS:              GNOME 45 Flatpak runtime
Arch:            x86_64
Kernel:          6.5.9-arch2-1
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             15.5 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 545.29.02
OpenGL Core:     4.6.0 NVIDIA 545.29.02
OpenGL ES:       OpenGL ES 3.2 NVIDIA 545.29.02
Vulkan Version:  1.3.261
Vulkan Drivers:  NVIDIA GeForce RTX 3060 Ti (1.3.260)

**Additional context**

**Comment by Goshko812** [comment]
do u have xdg-desktop-portal, xdg-desktop-portal-gnome and xdg-desktop-portal-gtk installed

**Comment by Goshko812** [comment]
and try restarting them
`systemctl --user restart xdg-desktop-portal
systemctl --user restart xdg-desktop-portal-gtk`

**Comment by TormStorm** [comment]
Addressed by #112
