### ISSUE TITLE
Installing via Lutris.

### ISSUE THREAD

**Issue by PapaFrankJr** [TormStorm/jagex-launcher-linux#118]
Cant download and install the runescape.sh file while trying to use the script from lutris website since the "raw.githubusercontent.com/TormStorm/jagex-launcher-linux/main/resources/runescape.sh" website comes with a 404 error.

**Comment by TormStorm** [comment]
The version on the Lutris website is very outdated, make sure to use the latest version from the release tab on GitHub: https://github.com/TormStorm/jagex-launcher-linux/releases
