### ISSUE TITLE
Lutris RuneScape 3 audio Crackling

### ISSUE THREAD

**Issue by nmlynch94** [TormStorm/jagex-launcher-linux#12]
# Problem
When launching RuneScape 3 in Flatpak, it has an audio crackle. In PulseAudio, this can be resolved by adding `--env='PULSE_LATENCY_MSEC=200'` as a `flatpak run` argument. This does not appear to work in pipewire and many distros are starting to have pipewire out of the box. 

See: https://github.com/flathub/com.jagex.RuneScape/issues/158
See: https://secure.runescape.com/m=forum/forums?409,410,514,66216866,5,346543089

The current behavior is a non-deterministic issue. If I launch over and over, I can get non-crackling audio about 1-2/10 times.

**Comment by Calmata** [comment]
For pipewire users, try adding --filesystem=xdg-run/pipewire-0    to your flatpak run arguments. This should re-enable pulse latency control under pipewire.

**Comment by nmlynch94** [comment]
Potential fix (workaround?) PR here https://github.com/flathub/com.jagex.RuneScape/pull/205. Not sure if this repo is still maintained but if it gets merged then this change should make setting PULSE_LATENCY_MSEC via cli args or flatseal work again. May need to tweak the value higher or lower depending on your system.

**Comment by nmlynch94** [comment]
The above PR was merged and now we can properly override that variable.
