### ISSUE TITLE
Install script not working

### ISSUE THREAD

**Issue by Nathant995** [TormStorm/jagex-launcher-linux#122]
I'm trying to install jagex launcher to lutris on linux;

when I run manually from an install file following OP's instructions I get error;
mapping values are not allowed here in <unicode string>
line 22 col 18;
mkdir_p(path)
             ^

here's the full def;

def mkdir_p(path):
    try:
        parent_path = Path(path)
        os.makedirs(parent_path.parent.absolute(), exist_ok=True)
    except OSError as exc:
        if exc.errno == errno.EEXIST and os.path.isdir(path):
            pass
        else: raise

**Comment by Nathant995** [comment]
Update:

Launcher.yml is missing from release but download source directly and the yml is present

**Comment by TormStorm** [comment]
Hello, the guide instructs you to download and extract the source code file where all of the release files are located.
