### ISSUE TITLE
Metafile isn't always a JWT

### ISSUE THREAD

**Issue by USA-RedDragon** [TormStorm/jagex-launcher-linux#126]
Related #125

The metafile that `launcher-win.production` refers to doesn't always seem to be a JWT. If you run this currently, it'll grab 

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/13051767/6015fe30-b68a-4f2f-a140-6365363ee589)

The file: http://jagex-akamai.aws.snxd.com/direct6/launcher-win/metafile/cc5e6fbd2073cf82e360e83127ffb076450e34b44a2dc3bda203b8e760c15a7e/metafile.json is the metadata it grabs

And the error
```
Latest metafile_url: http://jagex-akamai.aws.snxd.com/direct6/launcher-win/metafile/cc5e6fbd2073cf82e360e83127ffb076450e34b44a2dc3bda203b8e760c15a7e/metafile.json
  File "/tmp/tmp.pb87XpSy3D/jagex-launcher-linux/resources/installer.py", line 200, in <module>
    main()
  File "/tmp/tmp.pb87XpSy3D/jagex-launcher-linux/resources/installer.py", line 112, in main
    jwt = jwcrypto.jwt.JWT(jwt=jwt.decode("ascii"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/tmp.pb87XpSy3D/jagex-launcher-linux/venv/lib/python3.12/site-packages/jwcrypto/jwt.py", line 231, in __init__
    self.deserialize(jwt, key)
  File "/tmp/tmp.pb87XpSy3D/jagex-launcher-linux/venv/lib/python3.12/site-packages/jwcrypto/jwt.py", line 670, in deserialize
    raise ValueError("Token format unrecognized")
ValueError: Token format unrecognized
```

**Comment by nmlynch94** [comment]
Thanks for the report. I wonder why they changed that. I’ll have to think about how to otherwise validate that data since via TLS the certificate doesn’t match.

**Comment by USA-RedDragon** [comment]
I'll be curious to see if the next update has the JWT back or if it'll stay this way. Maybe Jagex just had a weird thing happen this release that might not appear in the future?

**Comment by USA-RedDragon** [comment]
Or use the base domain: https://jagex.akamaized.net/direct6/launcher-win/metafile/cc5e6fbd2073cf82e360e83127ffb076450e34b44a2dc3bda203b8e760c15a7e/metafile.json

**Comment by nmlynch94** [comment]
Yeah I got that other url from wireshark, so I wonder if they used to use the signed JWT instead of a cert to validate the data and fixed the url to match the cert this release. That would explain why it isn't a JWT anymore.
