### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by USA-RedDragon** [TormStorm/jagex-launcher-linux#128]
Currently, without a license in the repository this project is under "all rights reserved" (the by-law default, at least in the US where I live). Technically, the Flatpaks that use this (or any other project/fork) don't have a license to do so and we're infringing on your rights as the creator of the script and other resources available in this repo. (Edit: this resource made by GitHub explains it _much_ better than I did: https://choosealicense.com/no-permission/)

If you're not too familiar with open source licensing, GitHub has a good document that links some good resources (https://choosealicense.com/) about the topic: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Your choice of license mostly depends on what sorts of rights you might want to keep or provisions you might want any (forks/variants/projects using this) to follow.

For example, GPL requires (forks/variants/projects using this) to be GPL licensed as well, whereas MIT essentially requires (forks/variants/projects using this) to place attribution to the original source and creator.

Some notable licenses I've used are MIT, MIT-0 (MIT but with no attribution required), GPL v2 and v3, and my Jagex Launcher Flatpak source is using the FSF All Permissive License, but definitely don't take my word at face value for licenses and make the best decision for yourself :)

Thanks for attending my Ted Talk :joy:

**Comment by TormStorm** [comment]
Added a license :)
