### ISSUE TITLE
Possible silent install for Jagex Launcher

### ISSUE THREAD

**Issue by jolty1** [TormStorm/jagex-launcher-linux#14]
Maybe there is a launch parameter to silently install the Jagex Launcher so the user doesn't have to interact with the GUI. Which would help with the Lutris script. 

The Installer can be opened in an archive manager... but is encrypted, there is a file called **startQuiet.bat** maybe this allows for an unattended install. Of course this is speculation.

![Screenshot_20230516_205920](https://github.com/TormStorm/jagex-launcher-linux/assets/42779428/c8e45555-611c-41bc-8449-216854c26072)

**Comment by nmlynch94** [comment]
This is potentially interesting. Good find. I ran the installer in a windows VM and this gets unpacked into the temp dir during the installation. Here are the contents:

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/40608755/277b7243-c9ca-4ab6-86a5-abba587317d2)


Sorry for the screenshot. Guest tools aren't working correctly for copy paste. I'll run the installer again in procmon at some point and see if this ever gets called.
