### ISSUE TITLE
Timeout Waiting for Window To Load

### ISSUE THREAD

**Issue by jordan-josephs** [TormStorm/jagex-launcher-linux#22]
Problem:

I am trying to install jagex-launcher in Lutris using the script. Everything seems to download okay but when it goes to install, the installer window never pops up only ever displaying a window saying "Timeout waiting for window". Then it just quits with Code 256. I am using GNOME wayland so maybe that's an issue? I was just wondering if anyone has experienced this when trying to install. If any more information is needed please let me know. Cheers!

**Comment by TormStorm** [comment]
Did you try the troubleshooting step?

**Comment by NguyenTatDat21** [comment]
I have the same problem. I tried to remove and reinstalled proton many times but no luck.

**Comment by jordan-josephs** [comment]
@TormStorm  I did, with no such luck. I am confused as to which directory the /data/lutris/runners/wine is? If that is in reference to the flatpak version?

**Comment by TormStorm** [comment]
If you are using Flatpak the runner is located in: 
$HOME/.var/app/net.lutris.Lutris/data/lutris/runners/wine

If not it should be located in: 
$HOME/.local/share/lutris/runners/wine

If you are not using Flatpak it is recommended to install Wine locally and download the Lutris dependencies:
https://github.com/lutris/docs/blob/master/WineDependencies.md
You should also try to run the installer a few times, as it seems to be a bit inconsistent at the moment.
This is an issue that we are aware of, and are working to resolve.

**Comment by NguyenTatDat21** [comment]
I manage to fix the problem. After lutris finished downloading, before run the installer, I disable my internet. The Jagex launcher installer pop up after 1 minute. Then I turn the internet back on. The installing process run smoothly after that.

**Comment by jordan-josephs** [comment]
@NguyenTatDat21  I tried that with no such luck.

@TormStorm  I didn't have a wine folder there so I guess that isn't my issue. And I have tried the installer several times now all with the same result. I will keep trying new things and report back if I find a solution. Thanks guys!

**Comment by TormStorm** [comment]
@jordan-josephs What version of Lutris are you using and where did you download it from? Is it the Flatpak version, or did you get it from your distribution?

**Comment by jordan-josephs** [comment]
@TormStorm  Lutris 0.5.13 and its from Arch's repo's.

**Comment by jordan-josephs** [comment]
@TormStorm  So I have found something interesting. I spun up a Windows VM, installed Jagex-Launcher and copied the files over to my host, manually put them into the created jagex-launcher folder from the script and tried running that with no luck. I then discovered that it has to do with scaling. I have a 4k monitor which I usually have scaled to 150%, putting it back to 100% and viola, the Jagex Launcher appears! I have no idea what the bug is with that but I will look into it more and report back.

**Comment by jordan-josephs** [comment]
Okay so I have it working reliably now. I did the manual install as described above, and to get the launcher running reliably I enabled virtual desktop in lutris and set it to some manageable size for me like 1920x1080 and the launcher works perfectly, it launches runelite and rs3 just fine. Just wanted to put this here in case anyone else finds themself in this pickle!

**Comment by cernodile** [comment]
Adding this here to anyone else having same error - installing Lutris-packaged proton (GE8-7) instead of using system wine managed to get Jagex Launcher installer up and running.

**Comment by jordan-josephs** [comment]
@cernodile  I did try that and still couldn't get the window to appear outside the virtual desktop. I wonder if it has anything to do with the fact that I am on Nvidia.

**Comment by TormStorm** [comment]
@jordan-josephs What GPU you have shouldn't really matter, i use Nvidia myself. Have you also installed the recommended Wine dependencies? https://github.com/lutris/docs/blob/master/WineDependencies.md

**Comment by jordan-josephs** [comment]
@TormStorm  3080ti. I have all the depends installed. Idk what's going on with it but the main launcher will not load with the virtual desktop. The login will load but that's it.
