### ISSUE TITLE
Any way to use a non-flatpak RuneScape client?

### ISSUE THREAD

**Issue by AcouBass** [TormStorm/jagex-launcher-linux#23]
I've been trying to figure out how to do this without using the flatpak-installed version of the Runescape Launcher, as I already have it installed with my normal package manager - would there be any way to add this as an option? 

I tried editing your runescape.sh that launches the flatpak but I seem to get a lot of errors that I don't get when I just fire up the Runescape Launcher directly from the terminal so not sure where I'm going wrong!

**Comment by TormStorm** [comment]
We are working on a simpler way to do this. In the mean time you can open the system.reg file in $HOME/Games/jagex-launcher and delete the registry key below by searching for "RuneScape". After doing this relaunch the Jagex launcher and install RuneScape like normal.

``[Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\RuneScape Launcher_is1] 1685526834
#time=1d993a5cf91abb6
"InstallLocation"="C:\\Program Files (x86)\\Jagex Launcher\\Games\\RuneScape"``

**Comment by AcouBass** [comment]
So I'm understanding this correctly, does removing that registry key allow me to install the Runescape client via the Jagex launcher? So then it'd run the game via Wine instead of Flatpak?  

Is there no way to make this use the *native* version, installed via my Linux package manager?

**Comment by nmlynch94** [comment]
Hello! In theory, launching the native version with the script should work fine as far as I'm aware. The flatpak version is just the deb version wrapped in a flatpak runtime. I haven't tested it for myself, though. I'm away from my machine but will try tomorrow or the next day when I'm home and let you know if I can get it working!

In the meantime, we may be able to point you in the right direction if you post the error it is giving you here.

**Comment by nmlynch94** [comment]
Ok I tested this. I'm assuming you have flatpak Lutris installed? If so, I think the issue is just that the runescape-launcher executable is not available inside the flatpak sandbox. I tested it and it works if you change runescape.sh to:

`#!/bin/bash
flatpak-spawn --host --env=JX_ACCESS_TOKEN="$JX_ACCESS_TOKEN" \
              --env=JX_CHARACTER_ID="$JX_CHARACTER_ID" \
              --env=JX_DISPLAY_NAME="$JX_DISPLAY_NAME" \
              --env=JX_REFRESH_TOKEN="$JX_REFRESH_TOKEN" \
              --env=JX_SESSION_ID="$JX_SESSION_ID" runescape-launcher`
              
This tells flatpak to spawn a process outside of the sandbox and passes along all of the relevant authentication environment variables to keep single sign on working.

**Comment by AcouBass** [comment]
No I'm using a native Lutris install as well, not the flatpak version.  

My script is just a simple
`#!bin/sh
RuneScape`

(The "RuneScape" launch script on NixOS is named this rather than "runescape-launcher")  
 
I'm using NixOS so it's entirely possible there's some weirdness there mucking everything up. I'm getting the one that pops up in the Jagex launcher telling me to uninstall the game and re-install using the button in the launcher (pic attached), and a terminal output that looks like this:  


`2023-06-02 18:11:38,907: Starting Lutris 0.5.13
2023-06-02 18:11:38,908: Running AMD Mesa driver 23.0.3 on AMD Radeon RX 5700 XT (navi10, LLVM 15.0.7, DRM 3.52, 6.3.1-zen1) (0x731f)
2023-06-02 18:11:38,908: GPU: 1002:731F 1002:0B36 (amdgpu drivers)
2023-06-02 18:11:43,944: Unable to load libGLX_nvidia.so.0
2023-06-02 18:11:43,944: Unable to locate libGLX_nvidia
lutris-wrapper: Jagex Launcher
Started initial process 8744 from /home/eddie/.local/share/lutris/runners/wine/lutris-GE-Proton8-7-x86_64/bin/wine /home/eddie/Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher/JagexLauncher.exe
Start monitoring process.
wineserver: using server-side synchronization.
wine: Using setpriority to control niceness in the [-10,10] range
ntlm_auth: /home/eddie/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/fvysxy9ncxl8c3sg9hqyx24y05mhhm8r-samba-4.17.7/lib/samba/libcommon-auth-samba4.so)
ntlm_auth: /home/eddie/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/fvysxy9ncxl8c3sg9hqyx24y05mhhm8r-samba-4.17.7/lib/samba/libcommon-auth-samba4.so)
ntlm_auth: /home/eddie/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/fvysxy9ncxl8c3sg9hqyx24y05mhhm8r-samba-4.17.7/lib/samba/libcommon-auth-samba4.so)
ntlm_auth: /home/eddie/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/fvysxy9ncxl8c3sg9hqyx24y05mhhm8r-samba-4.17.7/lib/samba/libcommon-auth-samba4.so)
ntlm_auth: /home/eddie/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/fvysxy9ncxl8c3sg9hqyx24y05mhhm8r-samba-4.17.7/lib/samba/libcommon-auth-samba4.so)
ntlm_auth: /home/eddie/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/fvysxy9ncxl8c3sg9hqyx24y05mhhm8r-samba-4.17.7/lib/samba/libcommon-auth-samba4.so)
ntlm_auth: /home/eddie/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/fvysxy9ncxl8c3sg9hqyx24y05mhhm8r-samba-4.17.7/lib/samba/libcommon-auth-samba4.so)
ntlm_auth: /home/eddie/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/fvysxy9ncxl8c3sg9hqyx24y05mhhm8r-samba-4.17.7/lib/samba/libcommon-auth-samba4.so)
ntlm_auth: /home/eddie/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/fvysxy9ncxl8c3sg9hqyx24y05mhhm8r-samba-4.17.7/lib/samba/libcommon-auth-samba4.so)
ntlm_auth: /home/eddie/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /nix/store/fvysxy9ncxl8c3sg9hqyx24y05mhhm8r-samba-4.17.7/lib/samba/libcommon-auth-samba4.so)
wine client error:170: write: Bad file descriptor
Monitored process exited.
Initial process has exited (return code: 0)
Exit with return code 0
2023-06-02 18:11:56,018: Game still running (state: running)
2023-06-02 18:11:56,018: Stopping Jagex Launcher (wine)
2023-06-02 18:11:57,226: Shutting down Lutris
`
![Screenshot_20230602_180837](https://github.com/TormStorm/jagex-launcher-linux/assets/10049104/25f9822a-e529-49e7-88b9-67e8930baf3f)

**Comment by nmlynch94** [comment]
Hmm I know NixOS has some sort of reproducible packaging management. Do the applications themselves run in any sort of sandbox? Could be that Lutris doesn't have access to the RuneScape executable.

Maybe try doing the absolute path to the executable. I installed the nix package manager on my distro and was able to get it to launcher by doing 

```
#!/bin/sh
/nix/store/2q56j4v6ravlqfbl7sncx7hqpr1ib85q-RuneScape/bin/RuneScape
```
Which I found by doing `sudo find / -name "RuneScape"`

If I tried your script, it didn't work because the nixOS bin directory wasn't in the $PATH of whatever shell lutris was using to run this.

**Comment by AcouBass** [comment]
Hmm, yeah I tried that. My /nix/store/ location was different to yours but it was otherwise the same script. This issue is looking more and more like "NixOS weirdness" to be honest (Assuming this same setup has been tested on another distro)  

Having looked at the nixpkg for the runescape-launcher, it looks like they setup a containerized environment of some kind in which to run the "RuneScape" script, which in turn runs the actual "runescape" binary. So yeah, this is almost definitely NixOS weirdness rather than something broken in your Lutris script I think!

When changing the binary to the full /nix/store/ location it now fails with this error in the terminal, which is odd as launching the RS launcher direct from a terminal returns no such error. However I'm no longer getting the QUIT LAUNCHER error in the GUI which might be an improvement?

`/nix/store/nggldbldgijdmbrji27pnhyf4nb5q0sz-runescape-launcher-2.2.10/share/games/runescape-launcher/runescape: symbol lookup error: /usr/lib/libpango-1.0.so.0: undefined symbol: hb_ot_color_has_layers
`

Pointing the runescape.sh script in the Lutris directory to /nix/store/nggldbldgijdmbrji27pnhyf4nb5q0sz-runescape-launcher-2.2.10/share/games/runescape-launcher/runescape actually makes the game launch successfully! However with the size of the .sh script Nix installs to launch this binary there's a small amount of jankiness related to the environment variables and other things it sets (so no icons, the usual crackly sound issue, etc), so yeah there's definitely something in that launch script that doesn't like being launched via Lutris/Wine I suppose

**Comment by nmlynch94** [comment]
Ah ok gotcha. Sorry I'm very unfamiliar with NixOS so I don't have any other ideas. Am planning to learn about it one of these days.

**Comment by nmlynch94** [comment]
A YouTube channel I follow ended up releasing a video on nixOS and I looked into it a bit. I think you need to add RuneScape as a dependency in your Lutris installation in your configuration.nix file in order for it to have access to that executable and all its dependencies in its environment. Maybe in the package overrides? You probably know how to do this better than me as a nix user, but I’m pretty sure that’s the issue.

**Comment by Espionage724** [comment]
I haven't cleaned up the RS section yet, but I have some notes here on running Jagex Launcher through distro Wine and all 3 clients Linux native (OSRS with OpenJDK, RuneLite AppImage, and RS3 NXT), no Lutris: https://wiki.realmofespionage.xyz/games:wine:jagex_launcher

I only tested them on Fedora 38 but I don't see why it wouldn't work on other distros as-is outside of any RS3 NXT dependencies (needed OpenSSL compat), the Java path for OSRS, and distro-specific handling of AppImage for RL (didn't think it worked on Ubuntu 23.04).
