### ISSUE TITLE
Unable to type in login details after opening the launcher. 

### ISSUE THREAD

**Issue by zeakzzz** [TormStorm/jagex-launcher-linux#24]
selecting the enter email adress box highlights the outline of it with white dashes but does not allow for any inputs.

**Comment by TormStorm** [comment]
Sounds like a dependence issue. What version of Flatpak are you using, and where did you download it from?

**Comment by zeakzzz** [comment]
Im using the aur package, how can i check what dependancies im missing so i can install them?

**Comment by Repkap11** [comment]
I got around this by running the launcher exe with wine outside of Lutris. I used wine staging from https://wiki.winehq.org/Ubuntu but set to use the WINEPREFIX from Lutris.

Maybe you can switch Wine versions with Lutris, but I'm not very familiar with how Lutris works.

**Comment by nmlynch94** [comment]
Here are the dependencies lutris recommends https://github.com/lutris/docs/blob/master/WineDependencies.md. 

Also at the home screen of lutris, choose "Wine" under runners in the bottom left and click the cog. Under runner options, the script should have set  the Wine version to "lutris-GE-Proton8-7-x86_64". I've noticed on some systems it isn't doing this which we are looking into. 

If it is set to system or something, then close that screen and click the "Manage Versions" button to the left of the cog button, install that version of lutris, then go back into the cog settings and set Wine to that version.

**Comment by ChristineTilling** [comment]
To add a bit of information on the not setting the default version to lutris-GE-Proton8-7-x86_64, it did not install it and i couldn't find it at first under the settings, The solution to this: If you hover over the "Wine" under runners, there is a symbol of a list or window next to the cog, if you go into this menu you can choose to install the lacking version (or any other version really). Hope this helps in case someone else runs into it.

**Comment by zeakzzz** [comment]
> I got around this by running the launcher exe with wine outside of Lutris. I used wine staging from https://wiki.winehq.org/Ubuntu but set to use the WINEPREFIX from Lutris.
> 
> Maybe you can switch Wine versions with Lutris, but I'm not very familiar with how Lutris works.

using wine staging solved the issue, thanks!
