### ISSUE TITLE
Incompatible Wine version detected

### ISSUE THREAD

**Issue by nicoaarnio** [TormStorm/jagex-launcher-linux#27]
I'm using a Flatpak version in Lutris. Installation process goes without any issues except that known issue where you need to kill the installer manually. Then when I'm trying to launch the Jagex launcher I get this error and it won't start.
```
The Wine build you have selected does not support Esync. Please switch to an Esync-capable version.
```
and after I click "OK" the second pop-up shows up giving a following error:
```
Unhandled error: NON_ESYNC_WINE_VERSION
```

**Comment by nicoaarnio** [comment]
Okay I disabled Esync and Fsync and now it is running but I can't type or paste my email or password on that window. So there is another problem now.

**Comment by nmlynch94** [comment]
Sounds like it defaulted to the wrong version of wine. We have a submission to the lutris team with a fix so hopefully it will be approved soon. 

In the meantime, you fix fix by choosing the manage version button here:
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/40608755/5a803d0d-b378-4a8f-8dbc-40082ff8448b)

Make sure the latest lutris GE Proton version is downloaded.

Then right click on jagex launcher -> configure -> runner options and set wine version to lutris-GE-Proton8-x-x86_64

Re-enable fsync and esync then give that a shot.

**Comment by nicoaarnio** [comment]
> Make sure the latest lutris GE Proton version is downloaded.
> 
> Then right click on jagex launcher -> configure -> runner options and set wine version to lutris-GE-Proton8-x-x86_64

How do I get different wine versions? I Only have System (8.0) (default)?

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/30193510/6a3d414c-1a00-46c7-a364-3de27142936b)

**Comment by TormStorm** [comment]
Click the manage versions buttons as seen in the first picture and download lutris-GE-Proton8-x-x86_64

**Comment by nmlynch94** [comment]
@nicoaarnio did that fix your issue?

**Comment by nissan24zero** [comment]
Is there a video I can follow to set this up on my steam deck?

**Comment by nmlynch94** [comment]
There isn't currently a video, no. I've been toying with the idea of making one though so I'd be happy to do that if you'd find it useful.

**Comment by nissan24zero** [comment]
> There isn't currently a video, no. I've been toying with the idea of making one though so I'd be happy to do that if you'd find it useful.

Please!!!!
I tried setting it up myself but I couldn't figure it out and gave up :(
I would appreciate it so much,  I'd even make a donation if accepted and I got it working.

**Comment by nmlynch94** [comment]
Sure! I'll have some time later today and tomorrow and it shouldn't take long. I personally don't accept donations, although I don't know if @TormStorm does. He's the one who set this whole repo up so if anyone should get a donation, it'd be him 😄 .

We would also be curious to hear what parts in particular you found confusing so we can improve the guide. Feel free to open an issue with the feedback if you have it.

**Comment by nmlynch94** [comment]
Sorry for the bad quality, but hopefully this illustrates it well enough for you https://www.youtube.com/watch?v=Jx59wVSbTbk.

**Comment by nissan24zero** [comment]
Thank you,  I'll look into it as soon as I can,  probably in 3 days, I'm about to head to bed for work.  
Thanks for taking the time to make the for me,  I really appreciate you.

**Comment by nicoaarnio** [comment]
> @nicoaarnio did that fix your issue?

No there is no way to download anything.

**Comment by TormStorm** [comment]
> > @nicoaarnio did that fix your issue?
> 
> No there is no way to download anything.

Did you open the manage versions window?

**Comment by nmlynch94** [comment]
<img width="797" alt="image" src="https://github.com/TormStorm/jagex-launcher-linux/assets/40608755/2f84223c-1a68-4e5a-acc3-990ca84b0a06">

**Comment by nicoaarnio** [comment]
> <img alt="image" width="797" src="https://user-images.githubusercontent.com/40608755/246445823-2f84223c-1a68-4e5a-acc3-990ca84b0a06.png">

Worked, thanks! I haven't notice that button at all.
