### ISSUE TITLE
JagexLauncher.exe can't be found?

### ISSUE THREAD

**Issue by nicoaarnio** [TormStorm/jagex-launcher-linux#32]
Another issues.

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/30193510/88114f14-537d-42d8-8583-6b5aba2b0e52)

**Comment by nicoaarnio** [comment]
I installed Jagex Launcher to Windows VM and manually movent that in Launcher install in that specific folder and that fixed the issue. I remember this thing to be a part of the Bottle version install.

Should this Lutris script install Launcher automatically?

**Comment by nmlynch94** [comment]
Yeah it should. This either means the script crashed out in the previous step or you installed the Lutris installer to a non-empty directory. jagex’s installer should warn you if the directory isn’t empty so double check that window before continuing.
