### ISSUE TITLE
Steam deck issus

### ISSUE THREAD

**Issue by Akelly0002** [TormStorm/jagex-launcher-linux#34]
![IMG_4753](https://github.com/TormStorm/jagex-launcher-linux/assets/138053614/5fd74f77-1c0c-4759-b1cf-1323b3521705)

So I downloaded the ZIP file with the script and I run Lutris. But I keep getting the error “ failed to retrieve wine (lutris-GE-proton8-7-x86_64) information". I did some research and used proton up QT to install the version in “home/local/share/lutris/runners/wine” and still nothing. Same error. I also tried deleting and reinstalling Lutris.

**Comment by TormStorm** [comment]
Where did you download Lutris from? Highly recommend using the Flatpak version to prevent distro specific issue

**Comment by Akelly0002** [comment]
I downloaded it on the discover store

**Comment by Akelly0002** [comment]
![IMG_4755](https://github.com/TormStorm/jagex-launcher-linux/assets/138053614/bfef4d40-9d55-45f4-937b-df662d4e5e4d)

even with a fresh install off flat pack on the lutris website it pops the error. So weird.

**Comment by Akelly0002** [comment]
So I got it installed. I got past my issue. I can launch via desktop mode but in game mode it loads for a second and never launches. Any suggestions? It says launching exe then nothing

**Comment by TormStorm** [comment]
> ![IMG_4755](https://user-images.githubusercontent.com/138053614/249647398-bfef4d40-9d55-45f4-937b-df662d4e5e4d.jpeg)
> 
> even with a fresh install off flat pack on the lutris website it pops the error. So weird.

Look like Lutris dropped the version of Proton we were using, that might have been why you were having problems. I have just merged a pull request to update to a newer version of Proton.

**Comment by TormStorm** [comment]
> So I got it installed. I got past my issue. I can launch via desktop mode but in game mode it loads for a second and never launches. Any suggestions? It says launching exe then nothing

Not sure what this issue could be, maybe @nmlynch94 has an idea?

**Comment by Akelly0002** [comment]
Yes he ended up helping me. You guys are the best!

**Comment by TormStorm** [comment]
> Yes he ended up helping me. You guys are the best!

That's good to hear. Just out of curiosity what was the solution?

**Comment by nmlynch94** [comment]
I saw comments on the YouTube video before I saw this. This was how I discovered that GE Proton 8-7 was no longer supported.

the solution was to switch to 8-8 which is covered by the latest PR and he also had some issues with Boilr where he had to re-import the shortcut twice before it worked.

**Comment by Akelly0002** [comment]
Yeah he really helped me out when I saw his video. Thank you! It’s working now. Just trying to figure out how to resize the window so it fits the whole steam deck screen. Any ideas?
