### ISSUE TITLE
RuneLite.AppImage missing

### ISSUE THREAD

**Issue by BartDotRun** [TormStorm/jagex-launcher-linux#36]
When first installing the launcher through Lutris RuneLite worked just fine. However, when trying to start the Runelite client through the launcher after a system restart nothing happens when I press the blue 'play' button.

When checking the logs I see the following message: 
`/home/user/Games/jagex-launcher/dosdevices/c:/Program Files (x86)/Jagex Launcher/Games/RuneLite/RuneLite.exe: line 2: /home/user/Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher/Games/RuneLite/RuneLite.AppImage: No such file or directory`

**Comment by BartDotRun** [comment]
The problem is fixable by downloading the [.AppImage](https://github.com/runelite/launcher/releases/download/2.6.4/RuneLite.AppImage) manually, and setting the permissions manually again. However, I am not sure why the AppImage got removed in the first place.

**Comment by TormStorm** [comment]
I'm not sure what caused this, but i'm glad to hear you got it working again.
