### ISSUE TITLE
Update method

### ISSUE THREAD

**Issue by sdooweloc** [TormStorm/jagex-launcher-linux#38]
Is there a way to facilitate updates with the lutris install method? I see there have been changes to the repo since I installed but since we are installing from a custom script I dont think there is a way to get these updates without doing a full new install is that correct? Or am I missing something?

**Comment by TormStorm** [comment]
Hello, sorry for the late reply. I don’t think there is a way to update the Lutris installation, but the Jagex Launcher does automatically update, so as long as you got it working you shouldn’t need to reinstall.
