### ISSUE TITLE
Lutris Version

### ISSUE THREAD

**Issue by uweenukr** [TormStorm/jagex-launcher-linux#40]
I tried to install Lustris on KDE Neon and the Discover Store offered to install 0.5.9 which did not have the wizard that included "Install from a local install script" under the + button. I removed that installation and tried the flatpack which gave me 0.5.13 which did have the missing "Install from a local install script" under the + button.

I know some flavors may have different paths to get the software. So maybe just a minimum Lutris version listed?

**Comment by TormStorm** [comment]
The requirements links directly to the Flatpak version of Lutris, which is recommended to avoid distro specific issues. I could make it clearer that this is the version you should use.
