### ISSUE TITLE
Jagex Launcher won't run

### ISSUE THREAD

**Issue by deejcunningham** [TormStorm/jagex-launcher-linux#42]
I'm on Arch Linux. I've never used Flatpak so I might be missing something obvious. Installed flatpak via pacman and then flatseal and lutris via flatpak.

Install seems to have worked fine, but when I go to launch the Jagex Launcher (via `flatpak run net.lutris.Lutris` and then clicking the Jagex Launcher to run) flatpak/Lutris logs some errors and the operation eventually fails:

```
[dj@saturn ~]$ flatpak run net.lutris.Lutris
Gtk-Message: 12:28:41.869: Failed to load module "canberra-gtk-module"
2023-07-12 12:29:07,244: Starting Lutris 0.5.13
2023-07-12 12:29:07,246: Running AMD Mesa driver 23.1.1 on AMD Radeon RX 6800 XT (navi21, LLVM 15.0.7, DRM 3.52, 6.4.3-arch1-1) (0x73bf)
2023-07-12 12:29:07,246: GPU: 1002:73BF 1849:5201 (amdgpu drivers)
2023-07-12 12:29:12,486: Unable to load libGLX_nvidia.so.0
2023-07-12 12:29:12,486: Unable to locate libGLX_nvidia
Started initial process 64 from gamemoderun /home/dj/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-GE-Proton8-10-x86_64/bin/wine /home/dj/Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher/JagexLauncher.exe
Start monitoring process.
2023-07-12 12:29:32,401: Unable to start Settings portal: g-io-error-quark: Error calling StartServiceByName for org.freedesktop.portal.Desktop: Timeout was reached (24)
GameMode ERROR: D-Bus error: Could not call method 'RegisterGame' on 'org.freedesktop.portal.Desktop': Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
gamemodeauto: D-Bus error: Could not call method 'RegisterGame' on 'org.freedesktop.portal.Desktop': Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
GameMode ERROR: D-Bus error: Could not call method 'RegisterGame' on 'org.freedesktop.portal.Desktop': Failed to activate service 'org.freedesktop.portal.Desktop': timed out (service_start_timeout=120000ms)
gamemodeauto: D-Bus error: Could not call method 'RegisterGame' on 'org.freedesktop.portal.Desktop': Failed to activate service 'org.freedesktop.portal.Desktop': timed out (service_start_timeout=120000ms)
GameMode ERROR: D-Bus error: Could not call method 'RegisterGame' on 'org.freedesktop.portal.Desktop': Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
gamemodeauto: D-Bus error: Could not call method 'RegisterGame' on 'org.freedesktop.portal.Desktop': Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
```

I checked and I do indeed have `xdg-desktop-portal` and `xdg-desktop-portal-gnome` (and `xdg-desktop-portal-gtk` as a dependency thereof) installed. `printenv` shows that `XDG_CURRENT_DESKTOP=i3` because I use i3-gaps but my understanding is that things should properly default to one of the installed backends.

Kinda wish I had known this wasn't going to be straightforward or I would have not "upgraded" my account and just kept using runelite like I used to be able to 🙃.

**Comment by nmlynch94** [comment]
Do you by chance have a DE outside of i3 you could try this in? I don't think any of us have tested this using a WM and I've had weirdness with steam games in the past when trying to launch them with i3.

Yeah, agreed. I did the same thing which is what brought me to work on this project once I realized I was stuck -_-. In their latest blog post, they said they are looking at improving the process for linux users so hopefully some quality of life changes are coming soon.

**Comment by christophersherman** [comment]
I am having the exact same issue on i3 manjaro. Is functionality for i3 not implemented? This rabbit hole to play the game is getting deeper and deeper haha

**Comment by nmlynch94** [comment]
Yeah sorry you're having trouble. Another option is to try disabling Feral Gamemode with Right click -> configure -> System Options -> Enable Feral Gamemode.

**Comment by christophersherman** [comment]
Wow! thanks! Disabling feral gamemode allows me to launch successfully
Fantastic

**Comment by nmlynch94** [comment]
Great to hear!
