### ISSUE TITLE
Jagex Launcher under Lutris in BoilR

### ISSUE THREAD

**Issue by Vileblood18** [TormStorm/jagex-launcher-linux#44]
I've followed the guide up to importing the Jagex Launcher under Lutris in BoilR. I am not seeing the Jagex Launcher under Lutris in BoilR. Did I miss a step somewhere, or am I misreading the instructions?

**Comment by nmlynch94** [comment]
Are you talking about for the Steam Deck? That's the only time you need to use Boilr. If so, there is a guide here: https://www.youtube.com/watch?v=Jx59wVSbTbk you can compare steps against. You can also try right clicking in Lutris on the game -> Add steam shortcut and then rebooting. This used to be broken but they may have fixed it by now. 

Boilr is used so we can launch on the deck in game mode. On your PC you don't need that.

**Comment by TormStorm** [comment]
@Vileblood18 Did this solve the issue?
