### ISSUE TITLE
Crashing when using 2 accounts

### ISSUE THREAD

**Issue by jacob-rsmith** [TormStorm/jagex-launcher-linux#45]
I've been experiencing issues attempting to play on 2 accounts. I can open a 2nd game from the Jagex Launcher fine, and log in, but in <5 minutes after moving around the system will freeze and I have to force restart the PC. Is this an expected issue? I attempted to run a 2nd instance of the Jagex Launcher but that wouldn't even open for me.

**Comment by nmlynch94** [comment]
I tested playing two RuneLite accounts for 10 minutes and two RS3 accounts for 10 minutes. I didn't have any issues, so unfortunately I think this may be an instability with your system. 

Does an alt + f2 drop you into a terminal session, or is the system totally locked up?

**Comment by Calmata** [comment]
I've had issues ssimilar to this when running multiple applications alongside RuneScape under Linux that use hardware acceleration - second RuneScape instances, web browsers, Discord, that sort of thing. In my case it was a matter of insufficient video RAM and older hardware causing the problem - that's not to say it's the same problem, but it sounds suspiciously similar.

Could you tell us which distro and desktop environment you're using, your specs, and which game & client version(s) you're using (RS3/OSRS, vanilla/RuneLite)?

**Comment by jacob-rsmith** [comment]
@nmlynch94 I'll check the alt + f2 the next time I try. It seems like it's locked up, though the mouse will move _ever_ so slightly in one direction or another. I tried waiting it out once but didn't see an end.

**Comment by jacob-rsmith** [comment]
@Calmata 
OS: Kubuntu 22.04
Desktop: KDE Plasma 5.24.7

CPU: i5-8600k CPU @ 3.86
RAM: 8 GB (i know, been meaning to update it but it's difficult to get to and it's still alive so far)
GFX: GTX 1080 TI
Disk: NVME SSD, can find the specifics if needed

Game: 
both are Runescape 3 Accounts

**Comment by Calmata** [comment]
@jacob-rsmith 
On paper, you should be good hardware wise. Have you tried disabling the KDE compositor (Alt + Shift + F12)? It probably won't fix the underlying problem, but it may enable your system to stay stable under the added load till you can diagnose the problem.

Have you multiboxed before without using this project?

**Comment by TormStorm** [comment]
@jacob-rsmith Were you able to fix the issue?

**Comment by TormStorm** [comment]
Closed as stale. If you have any more information feel free to reopen the issue.
