### ISSUE TITLE
Runelite wont start from the launcher

### ISSUE THREAD

**Issue by TMKCodes** [TormStorm/jagex-launcher-linux#47]
I don't know what is wrong, Jagex Launcher starts, it installs vanilla client, but the runelite won't start.

**Comment by TMKCodes** [comment]
I can manually start the installed Runelite appimage when i'm on  ~/Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher and do sh Games/RuneLite/runelite.sh, but the Jagex client does not start it for some reason.

**Comment by TormStorm** [comment]
What distro are you using? Do you get any error messages when you try to start RuneLite from the Jagex Launcher?

**Comment by TMKCodes** [comment]
Running Manjaro Gnome. AFAIK the duplicate has a problem of not detecting, for me it gets detected but does not start. No errors that I can see.

**Comment by TMKCodes** [comment]
#!/bin/sh
set -e
flatpak run net.runelite.RuneLite || \
flatpak-spawn --host flatpak run \
    --env=JX_ACCESS_TOKEN="$JX_ACCESS_TOKEN" \
    --env=JX_CHARACTER_ID="$JX_CHARACTER_ID" \
    --env=JX_DISPLAY_NAME="$JX_DISPLAY_NAME" \
    --env=JX_REFRESH_TOKEN="$JX_REFRESH_TOKEN" \
    --env=JX_SESSION_ID="$JX_SESSION_ID" \
net.runelite.RuneLite

Though changing Runelite to use flatpak, works..
