### ISSUE TITLE
Must remove current RuneLite installation

### ISSUE THREAD

**Issue by simseeeee** [TormStorm/jagex-launcher-linux#48]
Hi,

I thought it'd be worth mentioning: If you have runelite installed before running the script it seems to break the installation.

I've just successfully got the script working after removing the runelite installation i already had, after trying multiple times to install via the script.

**Comment by nmlynch94** [comment]
Thanks for the report. When you say you have it installed, do you mean via your package manager or something similar? I wouldn't think that would affect it since the app uses a registry in wine which runs an AppImage file directly.

**Comment by TormStorm** [comment]
> Thanks for the report. When you say you have it installed, do you mean via your package manager or something similar? I wouldn't think that would affect it since the app uses a registry in wine which runs an AppImage file directly.

Does #50 fix this issue as well?

**Comment by simseeeee** [comment]
My installation of the jagex launcher has broken again even after removing my pre-existing installation of RuneLite, so there's something else I'm doing wrong here. Feel free to ignore this issue, I'll re-raise if It's an issue that isn't my own doing.

**Comment by TormStorm** [comment]
Ok, feel free to open a new issue if you have more problems.
