### ISSUE TITLE
Use flatpak runelite client

### ISSUE THREAD

**Issue by MithicSpirit** [TormStorm/jagex-launcher-linux#49]
Is there a way to convert this to use the flatpak for runelite rather than the appimage?

**Comment by nmlynch94** [comment]
Yep! Make sure the runelite flatpak is installed, and then edit the runelite.sh script in your lutris install dir (usually /home/myuser/Games).

So edit the file at /home/myuser/Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher/Games/RuneLite/runelite.sh and replace it with:

```
#!/bin/sh
set -e
flatpak run net.runelite.RuneLite || \
flatpak-spawn --host flatpak run \
    --env=JX_ACCESS_TOKEN="$JX_ACCESS_TOKEN" \
    --env=JX_CHARACTER_ID="$JX_CHARACTER_ID" \
    --env=JX_DISPLAY_NAME="$JX_DISPLAY_NAME" \
    --env=JX_REFRESH_TOKEN="$JX_REFRESH_TOKEN" \
    --env=JX_SESSION_ID="$JX_SESSION_ID" \
    net.runelite.RuneLite
```

This should launch runelite flatpak in flatpak and non-flatpak lutris.
