### ISSUE TITLE
Unable to interact with dropdown menus

### ISSUE THREAD

**Issue by fuzxi** [TormStorm/jagex-launcher-linux#51]
https://github.com/TormStorm/jagex-launcher-linux/assets/33790641/14f24364-3af6-42cf-9da9-8d200ea47cb3

I have tried Lutris-GE-Proton8-10, Wine-GE-Proton8-6, and Proton-GE-Proton8-10. I have tried uninstalling the launcher and rerunning the update script, both with and without Flatpak installed as well as with and without wine-staging installed through my package manager. This happens on both SwayWM and i3wm (I expected this was a Wayland bug, but apparently not). My distro is Manjaro.

**Comment by TormStorm** [comment]
Do you have a DE outside of Sway and i3 that you could try it on? Could be a VM issue.

**Comment by fuzxi** [comment]
Yeah, I can try a different one. Is there a "known good" one wrt the launcher?

**Comment by TormStorm** [comment]
I know that both Gnome and KDE work, probably others that work as well

**Comment by TormStorm** [comment]
Did you get it to work on a DE?

**Comment by fuzxi** [comment]
I haven't had the time to test yet. I'll update when I do.

**Comment by MushyMarks** [comment]
This is a wm bug but you should still be able to select with arrow keys.

**Comment by TormStorm** [comment]
Were you able to resolve this issue?

**Comment by banana-bred** [comment]
Similar behavior on Artix with DWM as my window manager. Clicking the dropdown menus appears to spawn a window, which dies almost immediately.

**Comment by ferreria23** [comment]
I have the same with i3, there is a workaround for this, set your jagex launcher window to toggle mode and the new window that allow you to select the option should.

**Comment by TormStorm** [comment]
Closed as a WM issue.
