### ISSUE TITLE
Jagex Launcher Stalls on Checking for launcher Updates

### ISSUE THREAD

**Issue by TWilldigg** [TormStorm/jagex-launcher-linux#54]
Followed instructions.

OS: Artix Linux, using window manager dk.
Runner: lutris-GE-Proton8-10
Hardware: Ryzen 5 2600X, Nvidia RTX 2070
Last working: Tuesday 25th July.

Small wine emulated box spawns top left.
Followed by main Jagex launcher in fullscreen.
With error on top saying:
"Unfortunately the Jagex Launcher was not able to start. Please check your connection and try restarting the launcher."
Upon clicking ok, it closes quickly before producing a large white window, that glitches.
Else, error disappears, launcher becomes unresponsive.

I've tried removing, and reinstalling to no avail.

Only difference is that I moved to a different part of the country, and updated my system packages, and osrs updated, I guess.

Side-thing:
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pipewire.so (/usr/lib32/alsa-lib/libasound_module_pcm_pipewire.so: cannot open shared object file: No such file or directory)
 
Is the only error in log, changed audio in lutris to use pulseaudio. No more error in log but same launcher behavior.

**Comment by TWilldigg** [comment]
After enabling debug info: 
03e0:err:winediag:process_attach Failed to load libgnutls, secure connections will not be available.

Seems to be the culprit.

**Comment by TWilldigg** [comment]
Installed libgnutls + winbind. 
Updated runner to 8-12 along with install script.
Launcher starts. Moved DXVK to version 2.8 in lutris.
Runelite works.

Not sure if DXVK is responsible as I did multiple changes.

Closing.

**Comment by TWilldigg** [comment]
Still ongoing. Got it working twice but unable to identify how or why. Seemingly random.

**Comment by TormStorm** [comment]
Could be a window manager issue, have you tried running it with a desktop environment to see if that works?

**Comment by nmlynch94** [comment]
@TWilldigg would need to see a debug log output to see if we can glean anything from that. You can turn on Output debugging info in Runner Options and then right click -> show logs. 

We had an issue in the past where the gamemode daemon did not start in i3 wm in manjaro. Doubt that's at play here since it works _sometimes_, but may be worth disabling to see if that gives you any luck.

**Comment by nmlynch94** [comment]
@TWilldigg Are you by chance on Wayland? I'm not sure what Artix defaults to, but we have seen inconsistent launch issues like this on Wayland systems. Either way, you could try out using wine-staging + virtual desktop - dxvk to see if you also get more consistency https://github.com/TormStorm/jagex-launcher-linux/issues/77#issuecomment-1698424278.

**Comment by TormStorm** [comment]
Closed as stale. If you have any more information feel free to reopen the issue.
