### ISSUE TITLE
Jagex Launcher not starting up - Initial process has exited (return code: 1280)

### ISSUE THREAD

**Issue by gxtav** [TormStorm/jagex-launcher-linux#55]
After I installed Jagex Launcher and tried to launch it and got that return code 1280 which I tried to look up but found nothing about, any ideas? 

Log for Jagex Launcher (wine):
Started initial process 6683 from /home/user/.local/share/lutris/runners/wine/lutris-GE-Proton8-12-x86_64/bin/wine /home/user/Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher/JagexLauncher.exe
Start monitoring process.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Initial process has exited (return code: 1280)
Monitored process exited.
Exit with return code 1280

I followed installing instructions but modified the installing script by changing "version: lutris-GE-Proton8-10-x86_64" to "version: lutris-GE-Proton8-12-x86_64"

**Comment by TWilldigg** [comment]
Jagex-Launcher > Configure > Runner Options > Output Debugging info > Enabled. Might help.

**Comment by Calmata** [comment]
@gxtav One of the project's contributors is testing the runner you switched to at present for regressions - have you successfully installed and launched the Jagex Launcher under ^-8-10-^?

**Comment by nmlynch94** [comment]
In addition to what @TWilldigg suggested, could you go to Lutris and select preferences -> hardware information then copy to clipboard and paste here. 

I Tested on an Ubuntu and Fedora machine but it worked so may be an OS-specific bug.

**Comment by TormStorm** [comment]
Have this issue been resolved? If not try to reinstall using the latest version of the script.

**Comment by TormStorm** [comment]
Closed as stale. If you have any more information feel free to reopen the issue.
