### ISSUE TITLE
Launcher opens, but attempting to launch RS3 fails

### ISSUE THREAD

**Issue by DeeeeLAN** [TormStorm/jagex-launcher-linux#59]
The game was working previously, but recently it stopped opening. 

When clicking play in the launcher, the RS3 game loader pops up for a second, but it never makes it to the login screen. When I run lutris from the command line, here is what is output when attempting to launch RS3 from the launcher:

```
/home/dillan/Games/jagex-launcher/dosdevices/c:/Program Files (x86)/Jagex Launcher/Games/RuneScape/RuneScape.exe: line 3: flatpak: command not found
gamemodeauto:
gamemodeauto:
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
ATTENTION: default value of option vblank_mode overridden by environment.
gamemodeauto:

** (process:8014): WARNING **: 14:21:40.964: Invalid client serial
dbus[407]: arguments to dbus_pending_call_block() were incorrect, assertion "pending != NULL" failed in file ../../dbus/dbus-pending-call.c line 766.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
```

I assume the dbus stuff isn't a big deal, but that "invalid client serial" line seems suspicious.

**Comment by DeeeeLAN** [comment]
Nevermind, I forgot I have to update flatpak packages separately. Running `flatpak update` fixed it.

**Comment by nissan24zero** [comment]
I haven't ever been able to get rs3 to load through the launcher besides in desktop mode. 
Couldn't ever figure out why,  but I'm genuinely interested if someone knows a way. 
I'll be following this post in hopes that there is a fix. 

I apologize my comment isn't helpful to your problem at all, I have just been trying for about a month with no real progress.
I miss rs3 on deck.
