### ISSUE TITLE
How to play rs3?

### ISSUE THREAD

**Issue by nissan24zero** [TormStorm/jagex-launcher-linux#61]
So I'm using the steam deck,  I've been trying for months to get rs3 to boot from the launcher with no luck. 

I've installed the flatpack for rs3, I'm not using the steam version. 
Osrs loads up just fine on runelite,  but when i hit play for rs3, it appears as though it's loading the client for a moment,  then stops and nothing happens. 

I would just use the steam client or other means without the launcher, unfortunately I merged my rs3 accounts to Jagex accounts without considering my steam deck,  so now I'm unable to play rs3 on deck without the launcher.

Any advice/info/videos or any other input would be greatly appreciated!

**Comment by nissan24zero** [comment]
That's the weird thing,  it loads fine in desktop mode. 
The launcher opens in both desktop and game mode. 
But I can't get rs3 to load in game mode,  just desktop mode. 
Something is just telling me I don't have something set up properly, but I'm not sure what that is. 
Sorry for the delayed reply, i never got the notification.

**Comment by nmlynch94** [comment]
I recommend using Steam for RS3 on the deck if at all possible. It's a much smoother experience IMO. 

I'm able to launch from steam. Only recommendation I have is maybe to swap to a GE wine version and see if that works. Could also try a factory reset of your deck as a nuclear option.

**Comment by nmlynch94** [comment]
@nissan24zero were you able to get this working?

**Comment by TormStorm** [comment]
Closed as stale. If you have any more information feel free to reopen the issue.
