### ISSUE TITLE
Ubuntu user is suddenly logged out while trying to extract "prefix" in the installation process 

### ISSUE THREAD

**Issue by kwaithex** [TormStorm/jagex-launcher-linux#63]
Hi! I'm having trouble installing on Ubuntu 22.04. Did everything in flatpak installation guide, installed lutris, went through installation steps. The installation script itself runs, downloading everything that was included in yml file. After everything is downloaded, dialog pops up "Extracting prefix", loader spins for about 10 seconds and then, without any information - screen just turns black and then user OS user selection screen pops up (Logged out). 

How can I debug what went wrong? And by the way, what exactly is prefix file that is included in the files section at installation script?
Thanks

Using: lutris-GE-Proton8-13

**Comment by TormStorm** [comment]
Hello, the prefix was something we tried to get around a bug in Lutris where it would time out on first installation when setting up Gecko, but it ended up with some different issues. I have just updated the script to a new version that removes the prefix, try this and see if that fixes the problem.

**Comment by TormStorm** [comment]
@kwaithex Were you able to resolve the issue?

**Comment by nmlynch94** [comment]
This should be addressed by #65.
