### ISSUE TITLE
256 Exit 

### ISSUE THREAD

**Issue by Broday9** [TormStorm/jagex-launcher-linux#64]
Hi,

I followed your directions to the T, until processing the install script through ROM.
I get the 256 exit code.

I then go to your guide on deleting HOME.var/app/net.lutris.Lutris/data/lutris/runners/wine" However I can't find it in Terminal, find out how to delete it in general. I know nothing about linux, this is the only laptop I have to play osrs. Please help, sorry if it's simple.

**Comment by TormStorm** [comment]
Hello, i have just updated the script to a new version to try to resolve this issue. Please try the latest version and see if that works,

**Comment by R-Dson** [comment]
I just tried it and got the same issue, for me it was that if $XDG_CACHE_HOME is not set, it tries to mkdir at /wine instead which it does not have access to.

**Comment by TormStorm** [comment]
That's good to hear, we recommend installing everything from the links provided in the repo for the best results. Were you able to launch the Jagex Launcher after installation?

**Comment by R-Dson** [comment]
Yes, it launches and so does RuneLite just fine.

Since OP couldn't find the Flatpak path, they probably have the same issue of not using the Flatpak version of Lutris.

**Comment by TormStorm** [comment]
@Broday9 Were you able to resolve the issue?

**Comment by R-Dson** [comment]
Just saw that another reason why OP might not find the correct directory might be because "$HOME.var/app/net.lutris.Lutris/data/lutris/runners/wine" is missing a / after $HOME in the README file.

**Comment by TormStorm** [comment]
The troubleshooting section has been moved to the wiki and the typo has been corrected, thanks for letting me know.

**Comment by TormStorm** [comment]
Addressed with #73
