### ISSUE TITLE
Black screen in lutris install window

### ISSUE THREAD

**Issue by KafoKajKodo** [TormStorm/jagex-launcher-linux#67]
Basically title, it sets up the wine prefix and then switches to a window with a blank log screen and does not progress. I've confirmed I have the right wine and am using the flatpak lutris. Using non-flatpak lutris it would show the script working but couldn't launch the actual jagex installer.

**Comment by nmlynch94** [comment]
Try running the installer like this `flatpak run net.lutris.Lutris -i jagexlauncher.yml` and post the logs here. 

You'll need to cd to the directory with the installer script and make sure Lutris is closed before it will work.

**Comment by KafoKajKodo** [comment]
https://pastebin.com/raw/YZQdRgbK

Here's the console output, ran in installer script directory. The text actually was displayed this time in the lutris installer window, but still no actual jagex window.

**Comment by nmlynch94** [comment]
@KafoKajKodo thank you for posting. It looks like the beginning may be cut off but I think I’ve got most of the important stuff. 

Could you please post your system specs? Should be in the Lutris preferences that you access from the top right. I’m mobile right now so can’t get the exact steps.

**Comment by KafoKajKodo** [comment]
`[System]
OS:              GNOME 44 Flatpak runtime
Arch:            x86_64
Kernel:          6.1.41-1-MANJARO
Desktop:         XFCE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
Physical cores:  4
Logical cores:   8

[Memory]
RAM:             5.7 GB
Swap:            8.8 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon Vega 8 Graphics (raven, LLVM 15.0.7, DRM 3.49, 6.1.41-1-MANJARO)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.4 (git-8b0202e4b4)
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.4 (git-8b0202e4b4)
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.4 (git-8b0202e4b4)
Vulkan Version:  1.3.224
Vulkan Drivers:  AMD Radeon Vega 8 Graphics (RADV RAVEN) (1.3.246)

`

Not sure if it's relevant but never used gnome on this computer just xfce, deleting xdg-desktop-portal-gnome removes 

2023-08-15 10:56:21,691: Unable to start Settings portal: g-io-error-quark: Error calling StartServiceByName for org.freedesktop.portal.Desktop: Timeout was reached (24)

but still no installer.

**Comment by nmlynch94** [comment]
@KafoKajKodo If you'd like, you can try to bypass the installer using this method https://github.com/TormStorm/jagex-launcher-linux/issues/75#issuecomment-1694724713 to see if you have any luck.

**Comment by TormStorm** [comment]
Closed as stale. If you have any more information feel free to reopen the issue.
