### ISSUE TITLE
Jagex Launcher cant find RuneLite.AppImage file 

### ISSUE THREAD

**Issue by TKafoe** [TormStorm/jagex-launcher-linux#72]
**Describe the bug**
RuneLite does not start when I click Play as the Jagex Launcher can not find the AppImage file.

In shell the output is the following: `drive_c/Program Files (x86)/Jagex Launcher/Games/RuneLite/RuneLite.AppImage: No such file or directory`.

However, when I run: `ls Program\ Files\ \(x86\)/Jagex\ Launcher/Games/RuneLite/` from the folder `drive_c`, the output is:
```
RuneLite.AppImage  RuneLite.exe  runelite.sh
```
So the file is there.

**To Reproduce**
1. Open Lutris through cli `flatpak run net.lutris.Lutris`.
2. Open the Jagex Launcher through Lutris
3. Click on Play when RuneLite is selected.
4. See error in shell.

**Expected behavior**
RuneLite should start.

**Please complete the following information:**
 - Distro: 
```
DISTRIB_ID="ManjaroLinux"
DISTRIB_RELEASE="23.0.0"
DISTRIB_CODENAME="Uranos"
DISTRIB_DESCRIPTION="Manjaro Linux"
``` 
 - Desktop environment or Window Manager:
```
plasmashell 5.27.6
Qt: 5.15.10
KDE Frameworks: 5.108.0
kf5-config: 1.0
```

**Comment by nmlynch94** [comment]
@TKafoe Are you able to launch the AppImage successfully if you cd to that folder and run `runescape.sh` manually? It won't log you in but want to make sure there is nothing wrong with the AppImage file itself.

**Comment by TKafoe** [comment]
Some more useful information:

If I add a `ls` to the `runelite.sh` file. I get the following output when I click Play in the Jagex Launcher.
```
chrome_100_percent.pak
chrome_200_percent.pak
chrome_elf.dll
d3dcompiler_47.dll
Games
icudtl.dat
installer.exe
JagexLauncher.exe
libcef.dll
libEGL.dll
libGLESv2.dll
locales
resources.pak
snapshot_blob.bin
v8_context_snapshot.bin
vk_swiftshader.dll
vk_swiftshader_icd.json
vulkan-1.dll
```
Which includes no folders, meaning that if I use the `$(pwd)` command, it will never find the AppImage file, as it indeed does not exist. If I use the exact path (without `$(pwd)`), I still does not work.

**Comment by nmlynch94** [comment]
@TKafoe Thank you for confirming. 

In your error message, you have `drive_c/Program Files (x86)/Jagex Launcher/Games/RuneLite/RuneLite.AppImage: No such file or directory`. That first path should be an absolute path including a home directory. Did you cut that off for privacy reasons, or is that the exact error message? If the latter, then there may be some special character in your path that the script isn't handling properly. If that's the case, I would need to see the full path, or at least something similar to it.

**Comment by TKafoe** [comment]
@nmlynch94 

> Did you cut that off for privacy reasons
Yes, I did. The full path contains `/home/...`. Now that I think of it, it was not very sensitive, but I cut it off out instinct.
The full path is the correct path to the file. I checked it.

**Comment by nmlynch94** [comment]
@TKafoe That's ok as long as you are sure it is right and it doesn't have any characters that could be messing up the bash interpreter. It just seems like `runelite.sh` is not getting a valid path somehow, presumably from pwd. 

You might be able to just edit runelite.sh to be and hard-code the path.

`cd <your_RuneLite.AppImage_location>`
`./RuneLite.AppImage`

**Comment by TKafoe** [comment]
@nmlynch94 `runelite.sh` does get the correct path through `$(pwd)`, as I can see that it does. I checked the path and it checks out. It simply does not find the file, even though it is there (even an `ls` shows the file being there). It feels like a permissions issue. I googled around, and I have found some posts that lead me to it being an issue because of previously installed wine versions on my computer (not through Lutris or Flatpak), so I will try to see if that leads me anywhere and post here if I get it to work.

**Comment by TKafoe** [comment]
Unfortunately, I can not find the issue. I am going to leave it unsolved for now. It is unfortunate that I can not play on RuneLite at the moment, but the normal client does work so I can use that.

I will close the issue, unless you have any other ideas.

**Comment by TKafoe** [comment]
Unfortunately, I can not find the issue. I am going to leave it unsolved for now. It is unfortunate that I can not play on RuneLite at the moment, but the normal client does work so I can use that.

I will close the issue, unless you have any other ideas.

**Comment by nmlynch94** [comment]
@TKafoe A couple things you could try:
Experimental repo running Jagex Launcher as a flatpak: https://github.com/nmlynch94/com.jagexlauncher.JagexLauncher

Adamcake's Bolt Launcher: https://github.com/Adamcake/Bolt (Native linux third party client. Logs you in then just launches the game with the correct auth tokens)
Adamcake's Bolt Launcher Flatpak: https://github.com/Adamcake/bolt-flatpak

Also, you could download the RuneLite jar file from the site (all platforms), place it in the directory with the AppImage, then see if you have any luck getting runelite.sh to run that instead. I haven't tested that so YMMV.
