### ISSUE TITLE
Timeout Waiting for Window To Load

### ISSUE THREAD

**Issue by SandWoodJones** [TormStorm/jagex-launcher-linux#76]
I've tried running the `.yml` a number of times already, with the same result: an error popup with `timeout waiting for window to load`, clicking "ok" will also show me the launcher's crash report dialog after a few seconds.
I tried following the troubleshooting wiki section, but it felt quite vague. I understood "run the installer again" as repeating the same steps and installing from a local install script on top of the failed installation, but I'm not sure if this is what I'm supposed to do.
I am using NixOS with plasma5.

**Comment by nmlynch94** [comment]
Hi @SandWoodJones Give this method a shot https://github.com/TormStorm/jagex-launcher-linux/issues/75#issuecomment-1694724713. 

There is some issue that causes that timeout waiting for windows to load to happen on some machines, sometimes. We think it's related to gecko, but haven't been able to nail down the exact cause. The above steps will allow you to bypass the installer and access the files directly.

**Comment by SandWoodJones** [comment]
I've tried installing the dependencies and using my system's lutris and installing lutris from flathub, both booted up the launcher but the "play" button is greyed out and I can't click it, and the character selection dialog is empty, if I click on it, a dropdown menu opens but it has no entries and is only a few pixels tall.
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/35671374/358175d3-9ed5-427a-bf3d-251a8f59dbee)

**Comment by nmlynch94** [comment]
@SandWoodJones In Lutris, Right click on the game -> Configure -> Game Options

put `--window --debug` in the Arguments section. Now run the launcher and reproduce the error. 

Please attach the file from the path at the top of the terminal window that opens. It'll be something like `/home/<you>/Games/jagex-launcher/drive_c/users/<you>/AppData/Local/Jagex Launcher/logs/host.developer.<date>.log`

**Comment by SandWoodJones** [comment]
Here you go: [host.developer.08.28.2023.log](https://github.com/TormStorm/jagex-launcher-linux/files/12457270/host.developer.08.28.2023.log)

**Comment by nmlynch94** [comment]
@SandWoodJones Does this happen on RuneScape as well, or just for OSRS?

**Comment by SandWoodJones** [comment]
I can install RuneScape which seems to be working, however, after installing the play button is greyed out and the dropdown still doesn't work.

**Comment by nmlynch94** [comment]
Ok thanks for confirming. I heavily suspect this is something to do with NixOS, however, I would have thought it would work in lutris flatpak. I'll have to setup a VM to test bc I've never seen this before.

**Comment by jzw2** [comment]
I am also using nixos, and can confirm that it is not working.  I am having the same `timeout waiting for window to load` error when running the lutris script. I also tried running it directly with wine, but it had the same timeout error. I also tried the script using the files download from media fire, but in that case, I cannot run it at all. I hit run and it just load forever.

**Comment by nmlynch94** [comment]
@jzw2 @SandWoodJones 
Ok I was able to get this working with this configuration. 

1. Install lutris with this configuration.nix setup: 
```
environment.systemPackages = with pkgs; [
    (lutris.override {
        extraPkgs = pkgs: [
            wineWowPackages.staging
            winetricks
            wineWowPackages.waylandFull
        ];
    })
];
```
2. Install jagex launcher using the mediafire method https://github.com/TormStorm/jagex-launcher-linux/issues/75#issuecomment-1694724713
3. Once complete, right click -> configure -> Runner options
4. Set Wine version to System (should be something like 8.5 Staging)
5. Disable DXVK, and Fsync
6. Enable Virtual Desktop

After this, I was able to get it to open consistently. I think this is mostly caused by wayland, so wine staging with the latest wayland support seems to be the best way to get it running. 

I was able to get it to launch sometimes without virtual desktop enabled, but it was inconsistent. Hopefully it works for you!

**Comment by SandWoodJones** [comment]
Hey, just as a follow up. I checked if the error still happened on windows, which it did, and realized that I had forgotten to link my existing characters (I blame Jagex for making the moving to the launcher process so convoluted). I'll check if this also fixes the error on NixOS later, which it probably does, but thanks for the support.

**Comment by nmlynch94** [comment]
Thank you! I wasn't aware that was what happened in this case, so good to have in case someone needs it in the future.

Would still be curious to hear if this works for you if you end up trying it @jzw2

**Comment by jzw2** [comment]
Unfortunately it did not work for me. It does not do the timeout error, but it still does not open any windows and just exits. The problem could potentially be unrelated to nixos though.

**Comment by nmlynch94** [comment]
Damn that sucks. If you want to provide a log from Lutris I can take a look. Other than that I’m out of ideas :(.
