### ISSUE TITLE
Jagex Launcher opens exactly once, then never again

### ISSUE THREAD

**Issue by willemkempers** [TormStorm/jagex-launcher-linux#77]
**Describe the bug**
I can open the Jagex launcher exactly once: after install. Each time after the Wine System Tray will open, but the Jagex Launcher never actually opens.

**To Reproduce**
1. Install Jagex Launcher according to provided instructions. I installed Runelite as well (flathub)
2. Open Jagex Launcher, log-in, do whatever
3. Quit Jagex Launcher
4. Try to relaunch. Nothing happens post Wine System Tray

**Expected behavior**
For Jagex Launcher to open

**Screenshots**

**Please complete the following information:**
 - Distro
 Fedora 38
 - Desktop environment or Window Manager
Gnome 44.4 Wayland

**Additional context**
I have `--window --debug` added in Game options -> Arguments. A console opens, and the line that stands out to me is:
```
08/29/2023 23:38:12 CONSOLE - WorkflowManager - Event Complete - {"successful":false,"cancelled":false,"errors":["Application_NotInstalled"],"name":"state","workflow":"82043825e88ea0438b99607843a7852d","exists":true,"global":true}
```
When I right-click on Lutris and click 'All Windows' there are 4 windows: Lutris, Wine System Tray, the debug console, and an OpenGL Renderer which doesn't show a window at all

**Comment by nmlynch94** [comment]
@willemkempers Ok I was able to get it running consistently on my end...but only via system wine with wine-staging installed. This seems to be a problem that is unique to gnome on Wayland. It works properly in Wayland on KDE. 

On Fedora 38 I installed wine as described here: https://github.com/lutris/docs/blob/master/WineDependencies.md and then in Lutris on the runners tab I disabled DXVK, set the runner to system wine (wine-staging), and then enabled the virtual desktop. These three changes seem to get the launcher opening consistently. You may need to full screen the launcher inside the virt desktop bc I was getting some weird mouse behavior.

**Comment by willemkempers** [comment]
Hmm so I've gone through those steps (installed wine using `sudo dnf install wine`), then clicked on the cog next to Wine in the Runners tab to open up the setting, set Wine version to 'System (8.0.2)' (from lutris-GE-Proton8-13-x86_64), disabled DXVK and set Windowed (virtual desktop) to `on` and saved.
When I click 'play', now nothing happens. The play button which turns to Stop once you press it, changes back to play after about 2 seconds. Not even a debug window opens. I tried setting the Virtual desktop resolution in the Wine configuration but that didn't help either.
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/1908890/5f0a9a7e-16d7-458c-b95f-3138af7f9212)

**Comment by nmlynch94** [comment]
Hmm strange. Would you be able to close Lutris, run it with ‘flatpak run net.Lutris.Lutris -d’ or just ‘Lutris -d’ if you don’t use flatpak, and see if there is an error when you press play?

Also I forgot to mention, but your debug logs look normal from what I can tell. That NotInstalled message prints every time.

**Comment by willemkempers** [comment]
Sure, that results in the appended output
[lutris-output.txt](https://github.com/TormStorm/jagex-launcher-linux/files/12476365/lutris-output.txt)

**Comment by nmlynch94** [comment]
Thanks you. Is the game still set to system wine? According to those logs it's still launching with lutris-GE-Proton8-13.

**Comment by willemkempers** [comment]
Next to the play button is an arrow button, if I click on that, then Configure I get another window. Then under the 'Runner options' tab the Wine version was still set to lutris-GE-Proton8-13. I switched that over to System as well, see attached output for the result. PATH issue?
[lutris-output-2.txt](https://github.com/TormStorm/jagex-launcher-linux/files/12476481/lutris-output-2.txt)

**Comment by nmlynch94** [comment]
Ah yep I didn't notice the first screenshot was the global wine settings. It will be overridden by individual app settings but you found the proper place. That error usually means there is a wine process that didn't properly exit. Try `wineserver -k` in a terminal and then launch again.

**Comment by willemkempers** [comment]
Nice seems to be working now! Thanks for your help! :-)

One last thing - where can I find the .runelite folder? I'd like to keep/migrate my settings, it used to be in `~/.runelite` but the flatpak version of runelite that gets launched through the launcher doesn't seem to recognize it

**Comment by nmlynch94** [comment]
So by default it uses the RuneLite.AppImage file, which in theory should use `~/.runelite`. Unless you swapped to using the RuneLite flatpak manually. If you did, then it will be either `var` or `~/.var`.

`sudo find / -name ".runelite"` should find all the folders on your system which might help. In RuneLite itself you can also do a profile import and see where it opens by default, which I think is in the .runelite folder.]

You could also export the profile from your working RuneLite, then import it in the jagex launcher version if that isn't working for some reason.

The easiest option I've found is to sign into RuneLite in the bottom right, and then enable cloud sync for the profile I want which I can then select on any clientr:
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/40608755/1effb10d-c5c3-4eb5-a059-0b836d25112d)
