### ISSUE TITLE
Runelite sometimes stops working with the launcher

### ISSUE THREAD

**Issue by IcelandicIcecream** [TormStorm/jagex-launcher-linux#79]
Hey guys, I've been using the jagex launcher for a while now and have had to reinstall a few times because I just cannot get into runelite sometimes. Is anyone else facing this issue as well?

Edit: the normal runescape client works fine

**Comment by nmlynch94** [comment]
Could you right click -> show logs in lutris, reproduce the issue, then post them here? 

This has not happened to me personally before.

**Comment by joewennesheimer** [comment]
I had the same issue. Looking at the log, it appears that it couldn't find the AppImage inside /home/{user}/Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher/Games/RuneLite/RuneLite.Appimage. What I noticed is that if I integrate the AppImage into my desktop, it moves the AppImage from the folder above, and moves it to my home/Applications folder. The way around this is to replace the AppImage inside the /home/{user}/Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher/Games/RuneLite/ folder, and then when prompted to integrate it into the desktop, just hit "Run once" each time. I know this isn't a fix, but it might help.

**Comment by nmlynch94** [comment]
@joewennesheimer Thank you for the information. @IcelandicIcecream Are you able to check the file path from his message and verify if the AppImage file is there?

**Comment by IcelandicIcecream** [comment]
@joewennesheimer @nmlynch94 can verify that it moves the Runelite AppImage to home/Applications. 
ERROR from logs: ./Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher/Games/RuneLite/RuneLite.AppImage: No such file or directory. 

Is there a better way to handle this change of directory? Or will it have to be configured from the install script?

**Comment by nmlynch94** [comment]
@IcelandicIcecream @joewennesheimer Sorry, I'm not sure how AppImage Launcher works. 

You could edit `runelite.sh` in the same dir as the appimage to launch it from wherever it's moved, make a symlink to the new location, or use RuneLite flatpak. 

If you aren't opposed to flatpak RuneLite, just install that and then edit runelite.sh to be this https://github.com/TormStorm/jagex-launcher-linux/issues/49.

**Comment by IcelandicIcecream** [comment]
> @IcelandicIcecream @joewennesheimer Sorry, I'm not sure how AppImage Launcher works.
> 
> You could edit `runelite.sh` in the same dir as the appimage to launch it from wherever it's moved, make a symlink to the new location, or use RuneLite flatpak.
> 
> If you aren't opposed to flatpak RuneLite, just install that and then edit runelite.sh to be this #49.

Cheers, I tried creating a symlink to the new location but it doesn't seem to work for some reason. So I just changed the directory in the runelite to point to the new location, this'll do for now haha
