### ISSUE TITLE
Launcher cant start runelite

### ISSUE THREAD

**Issue by jeroen11dijk** [TormStorm/jagex-launcher-linux#8]
After setting up the jagex launcher with bottles I get the following error:

![image](https://user-images.githubusercontent.com/17477730/231489582-7599f621-f8bf-4e4a-b857-70a0be8b4f44.png)

With my setup looking like:

![image](https://user-images.githubusercontent.com/17477730/231489268-52b30067-936c-4f3c-8f1c-bc5cf5b81e44.png)

Where the bash script does run RuneLite for me but I cant seem to figure out why the jagex launcher cant? Any help would be much appreciated

**Comment by TormStorm** [comment]
Have you checked that the locations for both the script and the registry entry are correct?

**Comment by jeroen11dijk** [comment]
I got it to work, my issue was that I copied the installation folder to:

/home/USERNAME/.var/app/com.usebottles.bottles/data/bottles/bottles/Jagex-Launcher/drive_c/Program Files (x86)

But I selected the launcher exe from the installation in home
