### ISSUE TITLE
Not able to login to runelite

### ISSUE THREAD

**Issue by saladuit** [TormStorm/jagex-launcher-linux#80]
**Describe the bug**
Opening runelite via the jagex launcher works perfectly. However, I'm not able to login to runelite. Is there another way to do so?

**To Reproduce**
1. Start jagex launcher
2. Click on 'Play'
3. Click 'Sign in to Runelite'
4. Nothing happens

**Expected behavior**
login popup menu

**Screenshots**
Not applicable

**Please complete the following information:**
```
                   -`                    saladuit@omega-arch 
                  .o+`                   ------------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: PCx0Dx 
               `+oooooo:                 Kernel: 6.4.12-zen1-1-zen 
               -+oooooo+:                Uptime: 9 mins 
             `/:-:++oooo+:               Packages: 1101 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.9 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           DE: GNOME 44.4 
         ./ooosssso++osssssso+`          WM: Mutter 
        .oossssso-````/ossssss+`         WM Theme: Adwaita 
       -osssssso.      :ssssssso.        Theme: Adwaita [GTK2/3] 
      :osssssss/        osssso+++.       Icons: Adwaita [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: guake 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i7-10870H (16) @ 5.000GHz 
  `+sso+:-`                 `.-/+oso:    GPU: Intel CometLake-H GT2 [UHD Graphics] 
 `++:.                           `-/+/   GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q 
 .`                                 `/   Memory: 5055MiB / 15686MiB 

                                                                 
                                                                 

```

**Comment by nmlynch94** [comment]
@saladuit This is working on my machine. All it does it launch an appimage, so I think maybe xdg-open + appimages aren't working on your system. 

If you run `xdg-open https://runelite.net`, does it open a browser window?

**Comment by saladuit** [comment]
@nmlynch94 seems to work!
```
~  ❯ xdg-open https://runelite.net

~  ❯ Opening in existing browser session.
```

**Comment by saladuit** [comment]
The following are the logs of lutris when starting the jagex launcher:
```
Started initial process 5293 from gamemoderun /home/saladuit/.local/share/lutris/runners/wine/lutris-GE-Proton8-13-x86_64/bin/wine /home/saladuit/Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher/JagexLauncher.exe
Start monitoring process.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
fsync: up and running.
wine: Using setpriority to control niceness in the [-10,10] range
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
gamemodeauto: 
gamemodeauto: 
gamemodeauto: 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.runelite.client.util.ReflectUtil (file:/home/saladuit/.runelite/repository2/client-1.10.11.1.jar) to field java.lang.reflect.Executable.declaredAnnotations
WARNING: Please consider reporting this to the maintainers of net.runelite.client.util.ReflectUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by saladuit** [comment]
i got the following from the logs, and clicking the green 'sign in to Runelite' butten doesn't add any entries. Also lookup wiki doesn't work.

**Comment by nmlynch94** [comment]
Could you try downloading and opening the AppImage file for runelite directly and seeing if browser links are working? I suspect this is unrelated to the jagex launcher, but that will confirm for sure.

**Comment by saladuit** [comment]
1. I downloaded runelite via pamac
2. started it
3. Was able to login
4. then launched runelite via the jagexlauncher
5. now i am logged in
6. but I am unable to for example use the wiki login

This kinda works for me at the moment as the settings are most important, but still curious why it doesn't work. @nmlynch94

**Comment by saladuit** [comment]
I'm just really unsure how to debug this

**Comment by nmlynch94** [comment]
Could you specifically launch the .AppImage file as opposed to the package manager version? 

You can cd to `/home/games/<you>/jagex-launcher/drive_c/Program FIles (x86)/Jagex Launcher/Games/RuneLite/` and there should be an appimage you can try to run with `./RuneLite.AppImage --appimage-extract-and-run`. This will isolate if it's a RuneLite appimage + distro issue or if it's something with how we launch it from the Jagex Launcher.

If that also doesn't work, then I'm honestly not sure how to debug it either unfortunately. There have been issues in the past with Appimages not allowing links to work on some distros https://github.com/keepassxreboot/keepassxc/issues/8721, but I don't know if a similar issue is at play here.

**Comment by saladuit** [comment]
@nmlynch94 Works!

**Comment by saladuit** [comment]
So it is probably not the distro

**Comment by saladuit** [comment]
It could be that I'm using brave? Is there somewhere specified which browser should be used?

**Comment by saladuit** [comment]
Note: @nmlynch94 I'm already very happy that I'm able to login, (quite yanky, but still). So many thanks for that!

**Comment by saladuit** [comment]
@nmlynch94 Sorry I hadn't seen your response yet. I'll check it!

**Comment by saladuit** [comment]
I think I did it correctly but it didn't seem to work?
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/43225170/0259bfb4-0011-421d-b257-0fa199f1b178)
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/43225170/24b824c4-a782-4b48-8989-d7211f6e0800)

**Comment by saladuit** [comment]
Oke I didn't follow the instructions correctly. So here is my revised settings:
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/43225170/858a814a-a020-45f7-9633-4a046b37fc95)
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/43225170/842dc5da-ce5c-419b-963c-7dcdba19e5ad)
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/43225170/4da2ab35-5976-4cc3-9fef-cef58cfaebeb)

At the moment the jagex launcher becomes totally black when trying to launch it.

**Comment by saladuit** [comment]
Oke the blackness was probably due to turning on prime render overload. the launcher luckily works again after restarting. Still curious to find out more about the browser settings though

**Comment by saladuit** [comment]
I'm on X11. I did use the arrow next to the wine glass this time. But it still doesn't use the correct browser. At this point I'm also unsure how to tackle this problem any further. Still if you know a fix I'm all ears! 

One small note, the explore.exe opens and the launcher opens in a separate window. Like this:
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/43225170/bf2a1e16-599f-4d11-b706-fdc6e2a6b9d2)

**Comment by rompetomp** [comment]
I have the same issue, and I tried the registry tweaks, but they don't solve the problem. Clicking the wiki button in RuneLite doesn't do anything and logging in only works when opening the AppImage directly.

FWIW, clicking a link inside the Jagex Launcher does open the webbrowser to the clicked link, it's just links in RuneLite that don't open.

**Comment by saladuit** [comment]
@rompetomp that is interesting. Because the links in my launcher also don't work...

**Comment by nmlynch94** [comment]
You could give this a shot and see if the links open in the flatpak version of runelite: https://github.com/TormStorm/jagex-launcher-linux/issues/49#issuecomment-1643221975. Downside is, even if it works, I'll have no idea why and we'll be no closer to finding the reason lol.

**Comment by TormStorm** [comment]
Try installing it with the latest installation script and see if that resolves the issue

**Comment by nmlynch94** [comment]
@Stoepsel3000 Seems likely. I'm on KDE as well so it would explain why I can't reproduce. I'll get cinnamon one of these days to see if I can get it working.

**Comment by TormStorm** [comment]
Closed as stale. If you have any more information feel free to reopen the issue.
