### ISSUE TITLE
Unable to move Runelite Overlays around holding "alt" key

### ISSUE THREAD

**Issue by WhatsTheIP** [TormStorm/jagex-launcher-linux#82]
**Describe the bug**
Unable to move Runelite Overlays around holding "alt" key, the overlays light up but whenever I try moving them to a different position it just moves the client around.

________________________________________________
**To Reproduce**
- 1. Log in
- 2. Hold alt to move "current hit overlay"
- 3. Client moves around vs. the overlay.

________________________________________________
**Expected behavior**
- Overlays should move, not the Runelite client

________________________________________________
**Screenshots**
NA, the client doesn't seem to dedicate I want to just move the overlays

________________________________________________
**Please complete the following information:**
```
      -/oooooooooooooooooooo+ooo/-         OS: Ubuntu Cinnamon 23.04 x86_64 
    .+oooooooooooooooooo+/-`.ooooo+.       Host: GS65 Stealth Thin 8RF REV:1.0 
   :oooooooooooo+//:://++:. .ooooooo:      Kernel: 6.2.0-32-generic 
  /oooooooooo+o:`.----.``./+/oooooooo/     Uptime: 3 hours, 21 mins 
 /ooooooooo+. +ooooooooo+:``/ooooooooo/    Packages: 2538 (dpkg), 15 (flatpak), 15 (snap) 
.ooooooooo: .+ooooooooooooo- -ooooooooo.   Shell: zsh 5.9 
/oooooo/o+ .ooooooo:`+oo+ooo- :oooooooo/   Resolution: 1600x900, 1920x1080 
ooo+:. .o: :ooooo:` .+/. ./o+:/ooooooooo   DE: Cinnamon 5.6.7 
oooo/-`.o: :ooo/` `/+.     ./.:ooooooooo   WM: Mutter (Muffin) 
/oooooo+o+``++. `:+-          /oooooooo/   WM Theme: Numix-Cinnamon-Semi-Transparent (Yaru-cinnamon-dark) 
.ooooooooo/``  -+:`          :ooooooooo.   Theme: Yaru-viridian-dark [GTK2/3] 
 /ooooooooo+--+/`          .+ooooooooo/    Icons: Yaru-viridian-dark [GTK2/3] 
  /ooooooooooo+.`      `.:++:oooooooo/     Terminal: konsole 
   :oooooooooooooo++++oo+-` .ooooooo:      CPU: Intel i7-8750H (12) @ 4.100GHz 
    .+ooooooooooooooooooo+:..ooooo+.       GPU: NVIDIA GeForce GTX 1070 Mobile 
      -/oooooooooooooooooooooooo/-         GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
        `-/oooooooooooooooooo/:`           Memory: 5906MiB / 31926MiB 
            .-:/++oooo++/:-.
```                                                                   
                                                                   
________________________________________________

**Additional context**
- wine-8.0.2
- Lutris version = 0.5.13

**Comment by ykrahsS** [comment]
There should be a setting in Cinnamon to disable the Special key to move windows.

**Comment by WhatsTheIP** [comment]
Thank you!!!

Here are the instructions for those who run into the same issue:
- To disable moving windows around when you hold the Alt key, open Cinnamon's start menu, go to Preferences and click on Windows. Switch to the Behavior tab at the top and change Special key to move and resize windows from <Alt> to <Super> or Disabled.
