### ISSUE TITLE
HDOS only supports flatpak

### ISSUE THREAD

**Issue by nmlynch94** [TormStorm/jagex-launcher-linux#84]
**Describe the bug**
HDOS will not launch in normal lutris in the current state. It calls flatpak-spawn instead only of using this method https://github.com/TormStorm/jagex-launcher-linux/blob/main/resources/runescape.sh#L3 which will fall back to flatpak-spawn if the flatpak command fails.

**To Reproduce**
Install Jagex Launcher in non-flatpak Lutris and run HDOS

**Expected behavior**
It should launch outside of flatpak-lutris

**Comment by TormStorm** [comment]
So it should look like this?

`
#!/bin/sh
set -e
flatpak run --env=PULSE_LATENCY_MSEC=200 \
    --env='vblank_mode=0' \
    --env='MESA_GL_VERSION_OVERRIDE=4.5FC' \
    dev.hdos.HDOS || \
flatpak-spawn --host flatpak run \
    --env=PULSE_LATENCY_MSEC=200 \
    --env='vblank_mode=0' \
    --env='MESA_GL_VERSION_OVERRIDE=4.5FC' \
    --env=JX_ACCESS_TOKEN="$JX_ACCESS_TOKEN" \
    --env=JX_CHARACTER_ID="$JX_CHARACTER_ID" \
    --env=JX_DISPLAY_NAME="$JX_DISPLAY_NAME" \
    --env=JX_REFRESH_TOKEN="$JX_REFRESH_TOKEN" \
    --env=JX_SESSION_ID="$JX_SESSION_ID" \
    dev.hdos.HDOS
`

**Comment by nmlynch94** [comment]
Yep, exactly.

**Comment by TormStorm** [comment]
Should be fixed now :)
