### ISSUE TITLE
Unable to launch HDOS with a Wayland (Hyprland) compositor

### ISSUE THREAD

**Issue by aestheticjmack** [TormStorm/jagex-launcher-linux#85]
**Describe the bug**
The installer doesn't work and an error appears

**To Reproduce**
1. Ran the script in lutris

**Expected behavior**

**Screenshots**

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/70598029/c19d27a9-b266-4dbe-b3b6-fc964d19dc4f)

**Please complete the following information:**
 - Distro - Arch  6.4.12-arch1-1
 - Desktop environment or Window Manager - Hyprland
 - Version - Unsure

**Additional context**

**Comment by aestheticjmack** [comment]
I restarted, re ran the script and it error'd out with 

```
4126 appears to have quit. Ending loop.
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0
Started initial process 7341 from /usr/bin/bash -c mkdir -p "/home/jmack/Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher/Games/"
Start monitoring process.
Monitored process exited.
Initial process has exited (return code: 0)
All processes have quit
Exit with return code 0
Started initial process 7681 from /usr/bin/bash -c ln -s "/home/jmack/Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher/Games/RuneLite/runelite.sh" "/home/jmack/Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher/Games/RuneLite/RuneLite.exe"
Start monitoring process.
ln: failed to create symbolic link '/home/jmack/Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher/Games/RuneLite/RuneLite.exe': File exists
Monitored process exited.
Initial process has exited (return code: 256)
All processes have quit
Exit with return code 256
```

link to full log https://pastebin.com/AVsYXdra

**Comment by aestheticjmack** [comment]
I installed dotnet48 via winetricks, it now shows up in lutris but gives me this error

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/70598029/9e96ef9b-1966-485a-bc09-c61f79d8cc67)

**Comment by aestheticjmack** [comment]
Followed this guide, downloaded the zip in his description and ran it with wine, looks to be working now

**Comment by aestheticjmack** [comment]
If anyone can help me figure out where to put HDOS in the folder structure I think I can get it all working, knew it was a mistake migrating my account ;_;

**Comment by aestheticjmack** [comment]
Putting HDOS.exe and hdos.sh in ~/jagex-launcher/Games/HDOS/ doesn't seem to do the trick

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/70598029/02fd06d3-3f05-4153-ae16-22de8118f2a4)

**Comment by nmlynch94** [comment]
@aestheticjmack Install the hdos flatpak and that should let you launch it.

**Comment by aestheticjmack** [comment]
> 

I do have it installed, I can run hdos.sh, or HDOS.exe, which is just an SL to the script and it launches HDOS, but the launcher fails to see HDOS

**Comment by nmlynch94** [comment]
Ah ok gotcha. Hmmm could you please check your registry? Highlight the game in lutris, click the up arrow next to the wine glass and select "Wine Registry". The entry that is used to detect HDOS should look like this:

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/40608755/94070b7f-e83f-496d-9a2b-08acb60a53fa)

**Comment by aestheticjmack** [comment]
Looks to be the same, also really appreciate the help (:

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/70598029/495e5a6b-abcf-4c8f-8cb6-cb1caf5df429)

**Comment by nmlynch94** [comment]
No problem!

Hmm that looks correct. I wonder if the launcher has a bug where it can't properly update from an older version to the one with HDOS support. Going to look at a couple things.

**Comment by aestheticjmack** [comment]
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/70598029/c012325d-4b02-46f7-abce-d10caa42b33f)

disabled mangohud, now the launcher works from lutris, I am using Hyprland which uses wayland which may be part of the culprit

HDOS is there but it does not launch it

**Comment by aestheticjmack** [comment]
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/70598029/46a4d8f7-2bd1-4c40-b57b-f3fc1aa12eea)


libEGL warning: egl: failed to create dri2 screen
flatpak: symbol lookup error: /usr/lib/libassuan.so.0: undefined symbol: gpgrt_malloc, version GPG_ERROR_1.0
/home/jmack/Games/jagex-launcher/dosdevices/c:/Program Files (x86)/Jagex Launcher/Games/HDOS/HDOS.exe: line 7: flatpak-spawn: command not found

this is the error I get when clicking play

**Comment by nmlynch94** [comment]
Ah, we have had a lot of issues with Wayland in this install.

It should be in your /home/Games folder by default. There will be the prefix, drive_c is equivalent to the C: drive you see in the registry entry. 

If you can get the play button for HDOS to show up, should should be able to right click -> show logs in lutris and get an error message to show what is stopping the script from launching. 

You may have more luck with this script if you want to try from scratch again. https://github.com/nmlynch94/jagex-launcher-linux/blob/patch-17/resources/jagexlauncher.yml. Tried some different DLL overrides. You can rename to destination to jagex-launcher1 or something to keep your working version for backup.

**Comment by nmlynch94** [comment]
Oh ok we actually just merged a fix for this yesterday, you must have downloaded the script right before. Make sure your HDOS.sh matches this: https://github.com/TormStorm/jagex-launcher-linux/issues/84.

**Comment by aestheticjmack** [comment]
It's the same, I downloaded the script maybe two hours ago

**Comment by aestheticjmack** [comment]
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/70598029/7ab1b204-b2c6-485a-8707-46926505cc42)
 
 
YAY

**Comment by nmlynch94** [comment]
Ok moment of truth. Does HDOS launch?

**Comment by aestheticjmack** [comment]
Had to disabled mangohud and gamescope for it to work, prob wayland issues, same error. I also gave it a different directory to work in so this should be from scratch

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/70598029/789b2ef5-551b-4025-8142-14b401dc723e)

**Comment by nmlynch94** [comment]
Your lutris isn't installed via nixPkgs by chance is it?

**Comment by aestheticjmack** [comment]
I don't use nix only the AUR, I installed flatpak just for this as I tend to stay away from that. I also tried changing wine versions but it would just crash.

Trying on a fresh lutris install with your recommendations

**Comment by nmlynch94** [comment]
Yeah fair enough. You can also edit hdos.sh in place and then hit the play button again on the working installation.

**Comment by aestheticjmack** [comment]
`flatpak: symbol lookup error: /usr/lib/libassuan.so.0: undefined symbol: gpgrt_malloc, version GPG_ERROR_1.0`

**Comment by nmlynch94** [comment]
Ah ha, there is the real culprit. I unfortunately have never seen that error before though lol so looking into it.

**Comment by aestheticjmack** [comment]
I don't think

```
ntlm_auth: /home/jmack/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /usr/lib/samba/libcommon-auth-samba4.so)
ntlm_auth: /home/jmack/.local/share/lutris/runtime/Ubuntu-18.04-x86_64/libjansson.so.4: no version information available (required by /usr/lib/samba/libcommon-auth-samba4.so)
```

is a part of it since it doesn't appear if I spam click the button

**Comment by aestheticjmack** [comment]
Runs it just fine

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/70598029/ed86f57c-f197-44c3-82a3-19a3e9c9edac)

**Comment by aestheticjmack** [comment]
All this work for linux users to get around this stupid credentials wrapper

**Comment by nmlynch94** [comment]
Yeah I know it's frustrating. There is a native launcher on flathub called Bolt that AdamCake created, but hdos doesn't have jdk 17 support so has not been integrated into it yet.

**Comment by nmlynch94** [comment]
Do you have these lutris deps installed? Not sure if the AUR takes care of that or not https://github.com/lutris/docs/blob/master/WineDependencies.md#archendeavourosmanjaroother-arch-derivatives. 

If you'd like, you could build Bolt from source to use your system java and provide it a custom .jar to run. It has a dropdown to select one. https://github.com/Adamcake/Bolt. Would let you avoid flatpak since you don't prefer them.

The other option is to try the lutris flatpak to see if this resolves whatever dependency issue the lutris runtime is having.

**Comment by aestheticjmack** [comment]
What's funny is I tried bolt but it can't see the .jar, probally a permissions issue, I'll try this lutris fix, I do have problems with tarkov and lutris but I played too much of that game so best I stay away from it.

**Comment by aestheticjmack** [comment]
lib32-libxslt-1.1.38-1 is the only package from there I have missing

**Comment by aestheticjmack** [comment]
Same error, don't know if I should try with the different hdos.sh if it's still throwing this

```[``](flatpak: symbol lookup error: /usr/lib/libassuan.so.0: undefined symbol: gpgrt_malloc, version GPG_ERROR_1.0)```

**Comment by nmlynch94** [comment]
Yeah it shouldn't make a difference. You'll need to put the original hdos.sh back if you swap to lutris flatpak, though.

**Comment by aestheticjmack** [comment]
I might as well try lutris flatpak at this point, I'll report back

**Comment by aestheticjmack** [comment]
I don't think this route is going to work well

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/70598029/220771f8-c204-4c9f-a7c8-c5e0052478bc)

**Comment by nmlynch94** [comment]
Try again if it installed gecko during that run. It sometimes times out after the gecko installation for some inane reason.

**Comment by aestheticjmack** [comment]
I did, no dice, I'll probally need to mess with flakpak a ton to get it working, tried building bolt as well and had no luck with that, at least I can play OSRS on runelite in the meantime, I'll post back in here if I have any updates. Switched to linux this year haven't touched windows since, had no problems until starfield and now this ;_;

**Comment by nmlynch94** [comment]
Did you get that from flathub? It's probably bc it's jdk 17.

`flatpak remove com.adamcake.Bolt`

Clone this repo https://github.com/Adamcake/bolt-flatpak

Modify the two highlighted lines in this screenshot
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/40608755/a10c3c96-a54a-414d-a21a-52cf52022b9c)

then build with the command in the readme in the repo (may need to install flatpak-builder) and run. I think that should get it running for you.

**Comment by aestheticjmack** [comment]
Looks like the shared-modules folder in that repo is empty?

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/70598029/04ac9302-6ec9-4544-8141-10f19175e74b)

**Comment by Adamcake** [comment]
Git doesn't clone submodules by default. `git clone --recurse-submodules https://github.com/adamcake/Bolt.git`

**Comment by Adamcake** [comment]
Sorry wrong repo, bolt-flatpak. You get the idea.

**Comment by aestheticjmack** [comment]
`git clone --recurse-submodules https://github.com/adamcake/bolt-flatpak.git` still gives empty directory

**Comment by aestheticjmack** [comment]
Deleted the folder and it pulled them, most likely because there was arleady a directory

**Comment by aestheticjmack** [comment]
Had to run `flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

Then it built

**Comment by aestheticjmack** [comment]
I'll close this thread, hopefully it helps other people on similar systems.
