### ISSUE TITLE
Could Flatpak Lutris install steps/common issues be added?

### ISSUE THREAD

**Issue by Peilonrayz** [TormStorm/jagex-launcher-linux#87]
A week or two ago I installed Lutris and Wine as native apps,  and installed from your Jagex Launcher Linux installer. Other than not installing all the native wine-gecko and wine-mono; installation went great.

However I've been migrating to Flatpak the past couple days. And have come around to re-installing the Jagex Launcher. I ran into a number of issues. Could a brief section be added to note common(?) errors when installing from a Flatpaked Lutris?

An example is provided below:

---

## Failed to retrieve wine (lutris-GE-Proton8-10-x86_64) information (#56)

Lutris currently has an issue where the correct wine version isn't installed automatically. Please see the next section.

## The Wine build you have selected does not support Esync. Please switch to an Esync-capable version. (#27)

1.  In Lutris under Runners, hover over "Wine" and click the "Manage Versions" button.
     ![Image showing Managed Versions location in Lutris.](https://user-images.githubusercontent.com/40608755/244528488-5a803d0d-b378-4a8f-8dbc-40082ff8448b.png)
2.  Look for the item which starts with "lutris-GE-Proton8-" followed by a number. For example "lutris-GE-Proton8-10", "lutris-GE-Proton8-14", etc.
3.  Ensure "lutris-GE-Proton8-xx" is installed.
4.  Reinstall the Jagex Launcher.

If you still get the error on reinstall:

5.  Navigate through Jagex Launcher -> Configure -> Runner options.
6.  Set "Wine version" to "lutris-GE-Proton8-xx-x86_64"

## Jagex Launcher doesn't start (D-Bus error: Could not call method 'RegisterGame' on 'org.freedesktop.portal.Desktop': Did not receive a reply.) (#42)

1.  Right click Jagex Launcher -> Show logs
2.  Verify a line like the following is showing:
    ```
    GameMode ERROR: D-Bus error: Could not call method 'RegisterGame' on 'org.freedesktop.portal.Desktop': Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
    gamemodeauto: D-Bus error: Could not call method 'RegisterGame' on 'org.freedesktop.portal.Desktop': Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
    ```
3.  Right click Jagex Launcher -> Configure -> System Options
4.  Disable "Enable Feral GameMode"

**Comment by TormStorm** [comment]
The first two problems are being tracked in #70 and should be fixed in the next version of Lutris. For now the installation script defines the runner version, so you should not need to install and select it manually.

Gamemode seem to be broken in Proton 8.X, so i can add this to the troubleshooting section of the wiki.

**Comment by TormStorm** [comment]
Updated the troubleshooting section of the wiki.
