### ISSUE TITLE
Jagex Launcher works but wont start the actual game

### ISSUE THREAD

**Issue by IcyMizore** [TormStorm/jagex-launcher-linux#89]
**Describe the bug**
Lutris will start up the jagex launcher fine but pressing play within the launcher does nothing.

 - Ubuntu
 - Desktop environment
 - Version 22.04.3 LTS

**Comment by nmlynch94** [comment]
Hi @IcyMizore. 

Make sure you have RuneLite and Runescape installed via flatpak as described in the readme instructions. If you do, then could you please right click on the game -> show logs. Then click play and paste the output here.

**Comment by CarterSheehan** [comment]
I’m having the same issue but only in big picture mode. In desktop mode the launcher and the game open up correctly.

**Comment by TormStorm** [comment]
> I’m having the same issue but only on my steam deck in big picture mode. In desktop mode the launcher and the game open up correctly.

There is an issue on this here #83, pull requests #100 will resolve this issue

**Comment by TormStorm** [comment]
Try to install it with the latest installation script an see if that resolves the issue

**Comment by turnipsoup** [comment]
I was able to fix this for myself by installing the flatpak version and changing the `runelite.sh` to this:

```
#!/bin/sh
#java -jar "$(pwd)"/Games/RuneLite/RuneLite.jar
flatpak run net.runelite.RuneLite
```

Could OP try this?

**Comment by IcyMizore** [comment]
I managed to fix it a while back, thanks everyone for helping out! And I'm sorry I don't know how to close the issue

**Comment by IcyMizore** [comment]
I fixed it, thanks everyone!

**Comment by aussiemcquackum** [comment]
> I was able to fix this for myself by installing the flatpak version and changing the `runelite.sh` to this:
> 
> ```
> #!/bin/sh
> #java -jar "$(pwd)"/Games/RuneLite/RuneLite.jar
> flatpak run net.runelite.RuneLite
> ```
> 
> Could OP try this?

This helped me out thanks
