### ISSUE TITLE
Bottles method add additonal filesystem access

### ISSUE THREAD

**Issue by jolty1** [TormStorm/jagex-launcher-linux#9]
Bottles sandboxes the users home directory by default.

So, Any existing config files, screenshots pretty much everything saved in ~/.runelite wont be seen.

`flatpak override com.usebottles.bottles --user --filesystem=~/.runelite` 

Will solve this. 

This be can verified by right clicking the Screenshot icon then Open folder... Before the override your File Manager wont open.

**Comment by jolty1** [comment]
I think a .runelite folder is suppose to be created in ~/.var/app/com.usebottles.bottles/ but it fails to do so.

https://github.com/flatpak/xdg-desktop-portal/issues/695#issue-1110351872

**Comment by jolty1** [comment]
Closing. 

All user files in flatseal is enough. 

Though, users with other multiple bottles may not want to expose their home directory to all of them.

**Comment by TormStorm** [comment]
Sorry for not addressing this issue. I have been exclusively focused on getting the Jagex launcher installer to work in Linux, which would solve this issue, but it took much longer to figure out than anticipated.
