### ISSUE TITLE
black screen when launching jagex launcher from lutrix

### ISSUE THREAD

**Issue by sirix123** [TormStorm/jagex-launcher-linux#90]
**Describe the bug**
I click play on the lutris launcher and the jagex launcher started up, I logged in and played the game, worked like normal but then on the second attempt to play I get a black screen when pressing play as per the screen shot. Restarting etc hasn't fixed it, have tried turning on and off feral game mode.

**To Reproduce**
1. open lutris
2. click play
3. black screen

**Expected behavior**
jagex launcher to load

**Screenshots**
atttached

**Please complete the following information:**
NAME="Nobara Linux"
VERSION="38 (Thirty Eight)"
ID=nobara
ID_LIKE="rhel centos fedora"
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Nobara Linux 38 (Thirty Eight)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=nobara-logo-icon
CPE_NAME="cpe:/o:nobaraproject:nobara:38"
HOME_URL="https://www.nobaraproject.org/"
DOCUMENTATION_URL="https://www.nobaraproject.org/"
SUPPORT_URL="https://www.nobaraproject.org/"
BUG_REPORT_URL=""
REDHAT_BUGZILLA_PRODUCT="Nobara"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Nobara"
REDHAT_SUPPORT_PRODUCT_VERSION=38
PRIVACY_POLICY_URL=""
VARIANT_ID=workstation

Logs:
```
(wine:15043): GStreamer-WARNING **: 12:16:17.301: Failed to load plugin '/home/stefans/.local/share/lutris/runners/wine/lutris-GE-Proton8-15-x86_64/lib/gstreamer-1.0/libgstflac.so': libFLAC.so.8: cannot open shared object file: No such file or directory
libEGL warning: egl: failed to create dri2 screen
``` 

![Screenshot from 2023-09-22 12-17-23](https://github.com/TormStorm/jagex-launcher-linux/assets/21241272/4bff7fa8-7b56-4741-8273-188f3c644864)

**Comment by TormStorm** [comment]
Hello, have you tried resizing the window?

**Comment by sirix123** [comment]
Hi, it won't even load now :(.  I press play it says play for a second, an icon on the task bar appears which says open gl or something then lutris says play again, nothing opens.

**Comment by TormStorm** [comment]
Try to close Lutris completely and make sure all of its processes are also closed, then try to open it again

**Comment by sirix123** [comment]
Tried that, it just does the same thing, I'm closing the processes via terminal etc. Same thing is happening.

**Comment by nmlynch94** [comment]
Hi @sirix123, can you please try these steps and see if that resolves the issue?  https://github.com/TormStorm/jagex-launcher-linux/issues/77#issuecomment-1698424278. We’ve seen this issue on Wayland, especially gnome Wayland if that’s the edition you’re using. You may need to adjust the steps to acquire wine-staging to work on Nobara, or it might come installed by default.

also, those gstreamer errors in proton ge are usually red herrings.

**Comment by nmlynch94** [comment]
@sirix123 No problem! Try the following:
1. If you have a machine with Nvidia Prime, try to enable prime render offload,
2. Enable advanced settings and then set the vulkan ICD file name. 

If those don't work, please post the hardware tab from your lutris preferences

**Comment by sirix123** [comment]
Hi, neither of those worked. Here is the info:
```
[System]
OS:              Nobara Linux 38 Thirty Eight
Arch:            x86_64
Kernel:          6.5.3-200.fsync.fc38.x86_64
Desktop:         GNOME
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           13th Gen Intel(R) Core(TM) i7-13620H
Physical cores:  10
Logical cores:   16

[Memory]
RAM:             15.3 GB
Swap:            16.8 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) Graphics (RPL-P)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.1.8
OpenGL Core:     4.6 (Core Profile) Mesa 23.1.8
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.8
Vulkan Version:  1.3.261
Vulkan Drivers:  Intel(R) Graphics (RPL-P) (1.3.261), NVIDIA GeForce RTX 4060 Laptop GPU (1.3.242)
```

**Comment by nmlynch94** [comment]
Thank you. Can you post the output of `nvidia-smi`?

**Comment by nmlynch94** [comment]
Also, when you set the ICD loader make sure you tried again with DXVK enabled. You should be setting it to your nvidia card in the dropdown.

**Comment by nmlynch94** [comment]
If you're not playing HDOS, you could also use https://flathub.org/apps/com.adamcake.Bolt which is a third party linux-native replacement for the jagex launcher. That would at least help isolate if it's a driver issue or something with wine. 

If you want to play HDOS on it, you still can but you'll have to build it yourself with java 11 instead of 17.

**Comment by sirix123** [comment]
Sorry I should have asked before what ICD am I picking from this list? 
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/21241272/74cd830a-78d4-486d-8990-6571a59aa1fa)
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/21241272/87865dc2-e0e2-4684-afb8-93165ca76a40)

Sorry what do you mean here in DXVK to set to my nvidia card? 
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/21241272/a3bbfe29-3d5e-4d15-a337-dd3849f9c0fb)

**Comment by nmlynch94** [comment]
Ok cool looks like your driver is setup properly.

Set Vulkan ICD loader to Nvidia Proprietary.

Then, try dxvk enabled with wine-staging + virt desktop
dxvk disabled with wine-staging + virt desktop
dxvk enabled with wine-ge
dxvk disabled with wine-ge

**Comment by sirix123** [comment]
Then, try dxvk enabled with wine-staging + virt desktop - play then stop (nothing happens)
dxvk disabled with wine-staging + virt desktop - play then stop (nothing happens)
dxvk enabled with wine-ge - play, icon appears in task bar but no window
dxvk disabled with wine-ge - play,  icon appears, window appears but black screen, tried resizing it etc, stays black

I downloaded bolt launcher and everything works fine, so I guess I will  just use that haha. Happy to keep testing stuff though in case it helps you track down the issue for future people.

**Comment by nmlynch94** [comment]
Glad that's working for you. Appreciate the willingness to test.

I suspect it's something about the configuration not properly offloading to your discrete gpu. Could also just be a wayland + wine bug though. Could you please enable debug logs in lutris, launch with show logs, then post here? Won't bug you anymore with debugging steps at that point but maybe I'lll notice somethin.

**Comment by sirix123** [comment]
Ok so strange, now it's starting up every time.. tried a lot.. but.. it lets me login and do 2FA but then the launcher window for the OS client is still black. Here is the log: 
```
[stefans@nobara-pc ~]$ lutris -d
2023-09-23 12:37:49,637: Command 'fluidsynth' not found on your system
INFO     2023-09-23 12:37:49,861 [startup.init_lutris:171]:Starting Lutris 0.5.13
INFO     2023-09-23 12:37:49,862 [startup.check_driver:64]:Using NVIDIA drivers 535.104.05 for x86_64
INFO     2023-09-23 12:37:49,862 [startup.check_driver:68]:GPU: NVIDIA GeForce RTX 4060 Laptop GPU
INFO     2023-09-23 12:37:49,862 [startup.check_driver:84]:GPU: 10DE:28E0 17AA:3C90 (nvidia drivers)
INFO     2023-09-23 12:37:49,862 [startup.check_driver:84]:GPU: 8086:A7A8 17AA:3C90 (i915 drivers)
INFO     2023-09-23 12:37:49,938 [api.get_default_runner_version:109]:Getting runner information for wine
DEBUG    2023-09-23 12:37:49,938 [http._request:88]:GET https://lutris.net/api/runners/wine
DEBUG    2023-09-23 12:37:51,939 [lutris.get_missing_game_ids:202]:Checking for missing games
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:__GL_SHADER_DISK_CACHE="1"
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:__GL_SHADER_DISK_CACHE_PATH="/home/stefans/Games/jagex-launcher"
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:DRI_PRIME="1"
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:__NV_PRIME_RENDER_OFFLOAD="1"
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:__GLX_VENDOR_LIBRARY_NAME="nvidia"
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:__VK_LAYER_NV_optimus="NVIDIA_only"
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/nvidia_icd.json"
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:LD_LIBRARY_PATH="/usr/lib:/usr/lib64:/lib64:/lib:/usr/lib64/ghc-9.2.6/lib/x86_64-linux-ghc-9.2.6:/usr/lib64/llvm15/lib:/usr/lib/llvm15/lib:/usr/lib64/fdk-aac:/usr/lib/fdk-aac:/usr/lib:/usr/lib64:/home/stefans/.local/share/lutris/runtime/Ubuntu-18.04-i686:/home/stefans/.local/share/lutris/runtime/steam/i386/lib/i386-linux-gnu:/home/stefans/.local/share/lutris/runtime/steam/i386/lib:/home/stefans/.local/share/lutris/runtime/steam/i386/usr/lib/i386-linux-gnu:/home/stefans/.local/share/lutris/runtime/steam/i386/usr/lib:/home/stefans/.local/share/lutris/runtime/Ubuntu-18.04-x86_64:/home/stefans/.local/share/lutris/runtime/steam/amd64/lib/x86_64-linux-gnu:/home/stefans/.local/share/lutris/runtime/steam/amd64/lib:/home/stefans/.local/share/lutris/runtime/steam/amd64/usr/lib/x86_64-linux-gnu:/home/stefans/.local/share/lutris/runtime/steam/amd64/usr/lib"
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:WINEDEBUG="-all"
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:DXVK_LOG_LEVEL="none"
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:WINEARCH="win64"
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:WINE="/usr/bin/wine"
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:WINE_MONO_CACHE_DIR="/home/stefans/.local/share/lutris/runners/wine/system/mono"
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:WINE_GECKO_CACHE_DIR="/home/stefans/.local/share/lutris/runners/wine/system/gecko"
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:WINEPREFIX="/home/stefans/Games/jagex-launcher"
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:WINEESYNC="1"
DEBUG    2023-09-23 12:38:30,950 [command.start:141]:WINEFSYNC="0"
DEBUG    2023-09-23 12:38:30,951 [command.start:141]:WINE_FULLSCREEN_FSR="1"
DEBUG    2023-09-23 12:38:30,951 [command.start:141]:DXVK_NVAPIHACK="0"
DEBUG    2023-09-23 12:38:30,951 [command.start:141]:DXVK_ENABLE_NVAPI="1"
DEBUG    2023-09-23 12:38:30,951 [command.start:141]:PROTON_BATTLEYE_RUNTIME="/home/stefans/.local/share/lutris/runtime/battleye_runtime"
DEBUG    2023-09-23 12:38:30,951 [command.start:141]:PROTON_EAC_RUNTIME="/home/stefans/.local/share/lutris/runtime/eac_runtime"
DEBUG    2023-09-23 12:38:30,951 [command.start:141]:WINEDLLOVERRIDES="d3d12,d3d12core,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,jscript.dll,nvapi,nvapi64=n;winemenubuilder="
DEBUG    2023-09-23 12:38:30,951 [command.start:141]:game_name="Jagex Launcher"
DEBUG    2023-09-23 12:38:30,951 [command.start:141]:PYTHONPATH="/usr/lib/lutris:/usr/lib64/python311.zip:/usr/lib64/python3.11:/usr/lib64/python3.11/lib-dynload:/usr/lib64/python3.11/site-packages:/usr/lib/python3.11/site-packages"
DEBUG    2023-09-23 12:38:30,951 [command.start:141]:LUTRIS_GAME_UUID="5c9d0c92-39ce-4617-a7f9-38f7d8ec24f9"
Started initial process 30043 from /usr/bin/wine /home/stefans/Games/jagex-launcher/drive_c/Program Files (x86)/Jagex Launcher/JagexLauncher.exe
Start monitoring process.
esync: up and running.

```

**Comment by nmlynch94** [comment]
Yeah that’s usually the point where wine-staging -dxvk + virtual desktop fixes it. It’d probably start working on x11 if you’re open to swapping to that.

**Comment by sirix123** [comment]
Yeah, what's x11 sorry? I'm happy to try it.

**Comment by nmlynch94** [comment]
If you click logout, when you click to enter your password there should be a dropdown in one of the corners of the screen that will let you swap from wayland to x11, assuming Nobara comes with x11 installed by default.

**Comment by sirix123** [comment]
I don't have that option when I logout they're all just variations of gnome.

**Comment by nmlynch94** [comment]
Choose this one that says gnome on xorg
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/40608755/8c2a64c5-16b0-4ad0-ba1f-7a5e1bb16c94)

**Comment by TormStorm** [comment]
Closed as stale. If you have any more information feel free to reopen the issue.
