### ISSUE TITLE
Discord Rich Presence Not Functioning

### ISSUE THREAD

**Issue by Isaacpop23** [TormStorm/jagex-launcher-linux#95]
**Describe the bug**

Runelite, only when opened through the Jagex Launcher, doesn't have proper Discord presence. Discord just recognizes it as an unknown game, giving it a generic status of "Playing runelite.appimage". 

**To Reproduce**

- Open Runelite through the Launcher with the Discord plugin enabled
- Check Discord game activity

**Expected behavior**

Proper Discord integration, showing what I'm doing in game, for how long, etc. As it does this when running Runelite from an appimage not tied to the Jagex Launcher.

 - Distro - Linux Mint
 - Desktop environment or Window Manager - XFCE
 - Version - 21.2

**Comment by TormStorm** [comment]
https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)
