### ISSUE TITLE
My JagexLauncher.exe keeps disappearing?

### ISSUE THREAD

**Issue by clscndd** [TormStorm/jagex-launcher-linux#96]
This happens after every normal Lutris installation via the script. I don't know what to do. Maybe someone could provide me with the .exe file?

![2023-10-01_19-15](https://github.com/TormStorm/jagex-launcher-linux/assets/100825734/5576beb9-6ded-4643-81bf-938b5f43220e)

**Comment by Calmata** [comment]
Hey there, I can try and resolve this with you, but I'm going to need to know a few things: 

Which distro are you using?
Are you using flatpak Lutris, or one provided by your distro's package manager?
Are you installing the Jagex Launcher project to your default (home) directory, or attempting to place it on a secondary drive?

**Comment by nmlynch94** [comment]
In addition, please clarify what behavior you are experiencing. When you say it "disappears", that implies it works at some point, but then the file vanishes. Is that the case? Or is the launcher installation not actually placing the file in the correct location.

**Comment by clscndd** [comment]
Hello, thanks for the answers! I considered your suggestions, but first tried right-clicking the Jagex Launcher on my Lutris interface and selecting "Install another version":

![image](https://github.com/TormStorm/jagex-launcher-linux/assets/100825734/0b5f25c1-4038-4e4c-8a65-9cd34fb088b4)

The first option guided me to a different installation and, after that, I was able to run the launcher successfully! All's well.

As for the original problem, yes, I was trying to place Jagex Launcher on a secondary drive (internal hard disk); and yes, I've been using a flatpak version of Lutris. For the record, I'm using Linux Mint 21.2. As for the .exe file, it was never present on the directories; I assumed it disappeared because it could not be found be Lutris.

Thank you again!
