### ISSUE TITLE
484 is still running. Continuing to check repository

### ISSUE THREAD

**Issue by Brxby** [TormStorm/jagex-launcher-linux#98]
**Describe the bug**
The installation is stuck at this line "484 is still running. Continuing to check directory"

I dont know any other way to explain it i just pressed install in Lutris and used the default directory.
Im attaching a screenshot:
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/120403978/d86c1703-2171-4dbc-a568-90a19c8bee10)

**Comment by TormStorm** [comment]
Hello, can you provide your hardware information?
In Lutris click the hamburger menu and select preferences, hardware information and copy this.

**Comment by Brxby** [comment]
[System]
OS:              GNOME 44 Flatpak runtime
Arch:            x86_64
Kernel:          5.15.117-19680-g54e910f94133
Desktop:         X-Generic
Display Server:  Not found

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Celeron(R) N4020 CPU @ 1.10GHz
Physical cores:  2
Logical cores:   2

[Memory]
RAM:             2.7 GB
Swap:            0.0 GB

[Graphics]
Vendor:          Mesa
OpenGL Renderer: virgl (Mesa DRI Intel(R) UHD Graphics 600 (GLK 2))
OpenGL Version:  4.3 (Compatibility Profile) Mesa 23.1.6 (git-0697ac0d75)
OpenGL Core:     4.3 (Core Profile) Mesa 23.1.6 (git-0697ac0d75)
OpenGL ES:       OpenGL ES 3.2 Mesa 23.1.6 (git-0697ac0d75)
Vulkan Version:  1.3.224
Vulkan Drivers:

**Comment by Brxby** [comment]
I tried running it again and now it says "1600 is still running. Continuing to check directory... Checking directory size..."

**Comment by Brxby** [comment]
I tried one last time and this time there were theese 2 errors:
First this one popped up while installing 
![image](https://github.com/TormStorm/jagex-launcher-linux/assets/120403978/2e1c1758-ec49-4f25-87d6-2055d3ff1ded)

And then when the installation finished this one popped up
![Screenshot 2023-10-03 5 01 12 PM](https://github.com/TormStorm/jagex-launcher-linux/assets/120403978/885d4bea-20a4-4ff2-a42b-b0b2cc36a0c2)

**Comment by Brxby** [comment]
Every time i run it it seems to give a different error. This time it was this:

Unhandled exception: page fault on read access to 0x00000028 in 32-bit code (0x00460270).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:00460270 ESP:0284e510 EBP:0284e528 EFLAGS:00010202(  R- --  I   - - - )
 EAX:00000004 EBX:00000000 ECX:00c07abc EDX:0284e578
 ESI:00000000 EDI:00000000
Stack dump:
0x0284e510:  172ac530 00000140 00000000 00000000
0x0284e520:  00000000 00000000 0284fe98 0044b419
0x0284e530:  00c07abc 025975f0 00000000 0284e578
0x0284e540:  0284e570 0284e580 172ac500 172ac530
0x0284e550:  172ac51a 00000000 00000000 00000000
0x0284e560:  0284e8e0 172ac530 00000000 7bc43d0c
Backtrace:
=>0 0x00460270 in jagex%20launcher%20installer (+0x60270) (0x0284e528)
  1 0x0044b419 in jagex%20launcher%20installer (+0x4b419) (0x0284fe98)
  2 0x0044d739 in jagex%20launcher%20installer (+0x4d739) (0x0284fef4)
  3 0x0053994b in jagex%20launcher%20installer (+0x13994b) (0x0284ff18)
  4 0x00539102 in jagex%20launcher%20installer (+0x139102) (0x0284ff30)
  5 0x7b62af70 in kernel32 (+0x2af70) (0x0284ff48)
  6 0x7bc5f2e7 in ntdll (+0x5f2e7) (0x0284ff5c)
  7 0x7bc5fbe0 in ntdll (+0x5fbe0) (0x0284ffec)
0x00460270 jagex%20launcher%20installer+0x60270: movl	0x28(%esi),%ecx
Modules:
Module	Address			Debug info	Name (114 modules)
PE	00400000-0062a000	Export          jagex%20launcher%20installer
PE	00e80000-00e8f000	Deferred        imagehlp
PE	01610000-01632000	Deferred        msacm32
PE	02540000-02542000	Deferred        usp10
PE	02c70000-02ebb000	Deferred        nss3
PE	02ec0000-02fcf000	Deferred        mozglue
PE	02fd0000-030e2000	Deferred        lgpllibs
PE	10000000-14572000	Deferred        xul
PE	61600000-61610000	Deferred        mspatcha
PE	61c40000-61c4d000	Deferred        userenv
PE	62500000-62639000	Deferred        oleaut32
PE	63580000-635c6000	Deferred        oleacc
PE	63880000-638aa000	Deferred        wintrust
PE	63900000-6390a000	Deferred        psapi
PE	63c00000-63c52000	Deferred        winhttp
PE	63cc0000-63f46000	Deferred        mshtml
PE	643c0000-643ea000	Deferred        ws2_32
PE	646c0000-646f6000	Deferred        iphlpapi
PE	64a80000-64abc000	Deferred        win32u
PE	65340000-6534a000	Deferred        msimg32
PE	65480000-65514000	Deferred        rpcrt4
PE	65680000-65731000	Deferred        msvcrt
PE	66080000-660dd000	Deferred        shlwapi
PE	66380000-664bf000	Deferred        ole32
PE	66640000-6664d000	Deferred        version
PE	667c0000-667da000	Deferred        shcore
PE	66f00000-66f90000	Deferred        ieframe
PE	67500000-6751f000	Deferred        imm32
PE	67bc0000-67d28000	Deferred        comctl32
PE	68100000-68111000	Deferred        sxs
PE	68280000-682a6000	Deferred        jsproxy
PE	684c0000-68523000	Deferred        combase
PE	68880000-68a3e000	Deferred        user32
PE	68cc0000-68d98000	Deferred        crypt32
PE	68e40000-68e6a000	Deferred        netapi32
PE	69000000-69091000	Deferred        gdiplus
PE	69840000-69884000	Deferred        advapi32
PE	69bc0000-69bd0000	Deferred        wsock32
PE	6aac0000-6ab9b000	Deferred        ucrtbase
PE	6aec0000-6af49000	Deferred        setupapi
PE	6b6c0000-6b703000	Deferred        msctf
PE	6ba40000-6ba53000	Deferred        odbccp32
PE	6bb40000-6bbb0000	Deferred        winex11
PE	6bbc0000-6bbee000	Deferred        sechost
PE	6bdc0000-6be0a000	Deferred        ia2comproxy
PE	6c100000-6c189000	Deferred        wininet
PE	6da80000-6db0a000	Deferred        gdi32
PE	6db80000-6dcf6000	Deferred        actxprxy
PE	6e000000-6e01e000	Deferred        cabinet
PE	6e200000-6e218000	Deferred        bcrypt
PE	6e3c0000-6e527000	Deferred        msi
PE	6ecc0000-6ecd6000	Deferred        dnsapi
PE	6f240000-6f308000	Deferred        winmm
PE	6f6c0000-6f6cc000	Deferred        nsi
PE	70000000-70068000	Deferred        dbghelp
PE	700c0000-700cb000	Deferred        dhcpcsvc
PE	70380000-70431000	Deferred        urlmon
PE	704c0000-704ce000	Deferred        dwmapi
PE	70d80000-70db7000	Deferred        uxtheme
PE	712c0000-712e0000	Deferred        mpr
PE	71400000-71d62000	Deferred        shell32
PE	7b000000-7b2ae000	Deferred        kernelbase
PE	7b600000-7b663000	Export          kernel32
PE	7bc00000-7bcb0000	Export          ntdll
ELF	7d000000-7d004000	Deferred        <wine-loader>
ELF	7e770000-7e79d000	Deferred        libexpat.so.1
ELF	7e79d000-7e7e8000	Deferred        libfontconfig.so.1
ELF	7e7e8000-7e80d000	Deferred        libgcc_s.so.1
ELF	7e80d000-7e82c000	Deferred        libz.so.1
ELF	7e82c000-7e86e000	Deferred        libpng16.so.16
ELF	7e883000-7e940000	Deferred        libfreetype.so.6
ELF	7e940000-7ea16000	Deferred        libm.so.6
ELF	7ea1c000-7ea25000	Deferred        libuuid.so.1
ELF	7ea25000-7ea2b000	Deferred        ws2_32.so
ELF	7ea2b000-7eba9000	Deferred        win32u.so
ELF	7eba9000-7ed31000	Export          libwine.so.1
ELF	e191d000-e1958000	Deferred        libtinfo.so.6
ELF	e1985000-e6a4d000	Deferred        libllvm-15.so
ELF	e7890000-e7896000	Deferred        netapi32.so
ELF	e7981000-e798e000	Deferred        libxcursor.so.1
ELF	e798e000-e7a12000	Deferred        libvulkan.so.1
ELF	e7a12000-e7a27000	Deferred        libxi.so.6
ELF	e7a27000-e7a2c000	Deferred        libxcomposite.so.1
ELF	e7a2c000-e7a3a000	Deferred        libxrandr.so.2
ELF	e7a3a000-e7a48000	Deferred        libxrender.so.1
ELF	e7a5d000-e7a8d000	Deferred        libxcb.so.1
ELF	e7a8d000-e7be5000	Deferred        libx11.so.6
ELF	e7be5000-e7bfc000	Deferred        libxext.so.6
ELF	e7bfc000-e7ca1000	Deferred        winex11.so
ELF	e7ca1000-e7cb4000	Deferred        libresolv.so.2
ELF	e7cb4000-e7ccc000	Deferred        libgpg-error.so.0
ELF	e7ccc000-e7dad000	Deferred        libgcrypt.so.20
ELF	e7dad000-e7dbd000	Deferred        libffi.so.8
ELF	e7dbd000-e7e48000	Deferred        libgmp.so.10
ELF	e7e48000-e7e80000	Deferred        libhogweed.so.4
ELF	e7e80000-e7ebd000	Deferred        libnettle.so.6
ELF	e7ebd000-e7ed2000	Deferred        libtasn1.so.6
ELF	e7ed2000-e8053000	Deferred        libunistring.so.2
ELF	e8053000-e8072000	Deferred        libidn2.so.0
ELF	e8072000-e81b6000	Deferred        libp11-kit.so.0
ELF	e81b7000-e81c0000	Deferred        libxfixes.so.3
ELF	e81c0000-e81c7000	Deferred        libxxf86vm.so.1
ELF	e81c7000-e81cb000	Deferred        libxinerama.so.1
ELF	e81cb000-e8362000	Deferred        libgnutls.so.30
ELF	e8362000-e8370000	Deferred        bcrypt.so
ELF	e837d000-e8382000	Deferred        librt.so.1
ELF	e8382000-e847c000	Deferred        ntdll.so
ELF	e847e000-e86b1000	Deferred        libc.so.6
ELF	e86b1000-e86b6000	Deferred        libdl.so.2
ELF	e86b6000-e86bb000	Deferred        libpthread.so.0
ELF	e86c0000-e86c6000	Deferred        libxau.so.6
ELF	e86c6000-e86ca000	Deferred        dnsapi.so
ELF	e86ca000-e86d0000	Deferred        crypt32.so
ELF	e86d2000-e870b000	Deferred        ld-linux.so.2
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 (D) Z:\home\[myuser]\.var\app\net.lutris.Lutris\cache\lutris\installer\jagex-launcher\jagexlauncher\Jagex%20Launcher%20Installer.exe
	["Z:\home\[myuser]\.var\app\net.lutris.Lutris\cache\lutris\installer\jagex-launcher\jagexlauncher\Jagex%20Launcher%20Installer.exe"]
	00000024    0     
	0000012c    0 <== 
	00000158    0     
	0000015c    0     
	00000160    0     
	00000164    0     
	00000168    0     
	0000016c    0     
	00000170    0     
	00000174    0     
	00000178    0     
	0000017c    0     
	00000180    0     
	00000184   -1     
	00000188   -1     
	00000190    0     wine_rpcrt4_server
	00000194    0     
	00000198    0     
	0000019c    0     
	000001a0    0     
	000001a4   -1     
	000001b0    0     
	000001b4    0     
	000001b8    0     
	000001bc    0     
	000001c0    0     
	000001c4    0     
	00000274    0     wine_rpcrt4_io
	0000027c    0     wine_wininet_collect_connections
	00000280    0     wine_rpcrt4_io
	00000284    0     
	00000288    0     
	000002c0    0     wine_threadpool_worker
	00000308    0     
00000030 services.exe
	00000034    0     
	00000038    0     wine_rpcrt4_server
	00000044    0     wine_rpcrt4_io
	00000068    0     wine_rpcrt4_io
	00000090    0     wine_rpcrt4_io
	000000a8    0     wine_rpcrt4_io
	000000bc    0     
	000000dc    0     wine_rpcrt4_io
0000003c winedevice.exe
	00000040    0     
	0000004c    0     
	00000050    0     wine_sechost_service
	00000054    0     
	00000058    0     
	0000005c    0     
	000000b4    0     
	000000b8    0     
00000060 winedevice.exe
	00000064    0     
	0000006c    0     
	00000070    0     wine_sechost_service
	00000074    0     
	00000078    0     
	00000084    0     
00000088 plugplay.exe
	0000008c    0     
	00000094    0     
	00000098    0     wine_sechost_service
	0000009c    0     wine_rpcrt4_server
000000a0 svchost.exe
	000000a4    0     
	000000ac    0     
	000000b0    0     wine_sechost_service
000000c0 explorer.exe
	000000c4    0     
	000000c8    0     
	000000cc    0     wine_rpcrt4_server
000000d4 rpcss.exe
	000000d8    0     
	000000e4    0     
	000000e8    0     wine_sechost_service
	000000ec    0     wine_rpcrt4_server
	000000f0    0     wine_rpcrt4_server
	000000f4    0     wine_rpcrt4_io
	00000138    0     wine_rpcrt4_io
	0000031c    0     wine_rpcrt4_io
000000fc tabtip.exe
	00000100    0     
	00000108    0     wine_rpcrt4_server
	0000010c    0     
	00000110    0     
00000300 conhost.exe
	00000304    0     
0000030c explorer.exe
	00000310    0     
	00000314    0     
	00000318    0     wine_rpcrt4_server
00000324 tabtip.exe
	00000328    0     
	00000330    0     wine_rpcrt4_server
	0000034c    0     
	00000354    0     
System information:
    Wine build: GE-Proton8-15 (Staging)
    Platform: i386 (WOW64)
    Version: Windows 10
    Host system: Linux
    Host version: 5.15.117-19680-g54e910f94133

**Comment by Brxby** [comment]
This time I got an error code: Exit with return code 256
I dont think this is getting anywhere

**Comment by nmlynch94** [comment]
Hi @Brxby. Could you please try running your installer from the cli like this `flatpak run --env="WINEDEBUG=+loaddll,+seh,+error" net.lutris.Lutris -i jagexlauncher.yml &> out.log`

And then attach the out.log file here?

Also, what OS are you running? Lutris is saying it can't detect your display server according to the hardware info you posted, which could be an issue.

**Comment by Brxby** [comment]
Yea i figured the OS might have something to do with it. Im actually running linux on a chromebook so idk if thats a problem.

**Comment by Brxby** [comment]
[out.log](https://github.com/TormStorm/jagex-launcher-linux/files/12793738/out.log)
Heres the outlog.

**Comment by nmlynch94** [comment]
That log file didn't work, looks like it's only 3 lines. 

Make sure your existing instance of Lutris is closed and then try running it again.

**Comment by Brxby** [comment]
[out.log](https://github.com/TormStorm/jagex-launcher-linux/files/12793868/out.log)
There, this one should be fine.

**Comment by Brxby** [comment]
I just used Bolt so i dont need help anymore
